import { defineMessages } from 'react-intl';

export default defineMessages({
  statusBreakdown: {
    id: 'app.containers.Admin.projects.project.insights.statusBreakdown',
    defaultMessage: 'Status Breakdown',
  },
  noInputsSubmitted: {
    id: 'app.containers.Admin.projects.project.insights.noInputsSubmitted',
    defaultMessage: 'No inputs have been submitted yet.',
  },
  topicsAndThemes: {
    id: 'app.containers.Admin.projects.project.insights.shared.topics',
    defaultMessage: 'Topics',
  },
  noTopics: {
    id: 'app.containers.Admin.projects.project.insights.shared.noTopics',
    defaultMessage: 'No topics assigned to inputs yet',
  },
  unlockTopicClustering: {
    id: 'app.containers.Admin.projects.project.insights.shared.unlockTopicClustering',
    defaultMessage: 'Unlock topic clustering',
  },
  upsellTooltipMessage: {
    id: 'app.containers.Admin.projects.project.insights.shared.upsellTooltipMessage',
    defaultMessage:
      'This feature is not included in your current plan. Talk to your Government Success Manager or admin to unlock it.',
  },
  topicBreakdown: {
    id: 'app.containers.Admin.projects.project.insights.shared.topicBreakdown',
    defaultMessage: 'Topic Breakdown',
  },
  aiPowered: {
    id: 'app.containers.Admin.projects.project.insights.shared.aiPowered',
    defaultMessage: 'AI-Powered',
  },
  aiTopicDistribution: {
    id: 'app.containers.Admin.projects.project.insights.shared.aiTopicDistribution',
    defaultMessage: 'AI Topic Distribution',
  },
  manualTagsByParticipants: {
    id: 'app.containers.Admin.projects.project.insights.shared.manualTagsByParticipants',
    defaultMessage: 'Manual Tags by Participants',
  },
  topicsAutoDetected: {
    id: 'app.containers.Admin.projects.project.insights.shared.topicsAutoDetected',
    defaultMessage: 'Topics automatically generated by AI from idea content',
  },
  noAiTopics: {
    id: 'app.containers.Admin.projects.project.insights.shared.noAiTopics',
    defaultMessage: 'No AI topics generated yet',
  },
  noManualTags: {
    id: 'app.containers.Admin.projects.project.insights.shared.noManualTags',
    defaultMessage: 'No manual tags assigned yet',
  },
  unlockAiTopicClustering: {
    id: 'app.containers.Admin.projects.project.insights.shared.unlockAiTopicClustering',
    defaultMessage: 'Unlock AI Topic Clustering',
  },
  aiTopicClusteringDescription1: {
    id: 'app.containers.Admin.projects.project.insights.shared.aiTopicClusteringDescription1',
    defaultMessage:
      "Automatically organize all inputs into meaningful themes, even when participants don't tag them.",
  },
  upgradeYourPlan: {
    id: 'app.containers.Admin.projects.project.insights.shared.upgradeYourPlan',
    defaultMessage: 'Upgrade your plan',
  },
  manualTagsSummary: {
    id: 'app.containers.Admin.projects.project.insights.shared.manualTagsSummary',
    defaultMessage: '{taggedCount} inputs · {topicsCount} topics',
  },
  aiTopicsSummary: {
    id: 'app.containers.Admin.projects.project.insights.shared.aiTopicsSummary',
    defaultMessage: '{inputsCount} inputs · {topicsCount} topics',
  },
});
