import { defineMessages } from 'react-intl';

export default defineMessages({
  statusBreakdown: {
    id: 'app.containers.Admin.projects.project.insights.statusBreakdown',
    defaultMessage: 'Status Breakdown',
  },
  noInputsSubmitted: {
    id: 'app.containers.Admin.projects.project.insights.noInputsSubmitted',
    defaultMessage: 'No inputs have been submitted yet.',
  },
  topicsAndThemes: {
    id: 'app.containers.Admin.projects.project.insights.shared.topics',
    defaultMessage: 'Topics',
  },
  noTopics: {
    id: 'app.containers.Admin.projects.project.insights.shared.noTopics',
    defaultMessage: 'No topics assigned to inputs yet',
  },
  topicClusteringUpsellDescription: {
    id: 'app.containers.Admin.projects.project.insights.shared.topicClusteringUpsellDescription',
    defaultMessage:
      'Cluster ideas in real time from participants into topics & subtopics and get summaries to better navigate conversations at scale',
  },
  unlockTopicClustering: {
    id: 'app.containers.Admin.projects.project.insights.shared.unlockTopicClustering',
    defaultMessage: 'Unlock topic clustering',
  },
  upsellTooltipMessage: {
    id: 'app.containers.Admin.projects.project.insights.shared.upsellTooltipMessage',
    defaultMessage:
      'This feature is not included in your current plan. Talk to your Government Success Manager or admin to unlock it.',
  },
  topicBreakdown: {
    id: 'app.containers.Admin.projects.project.insights.shared.topicBreakdown',
    defaultMessage: 'Topic Breakdown',
  },
  aiPowered: {
    id: 'app.containers.Admin.projects.project.insights.shared.aiPowered',
    defaultMessage: 'AI-Powered',
  },
  aiTopicDistribution: {
    id: 'app.containers.Admin.projects.project.insights.shared.aiTopicDistribution',
    defaultMessage: 'AI Topic Distribution',
  },
  manualTagsByParticipants: {
    id: 'app.containers.Admin.projects.project.insights.shared.manualTagsByParticipants',
    defaultMessage: 'Manual Tags by Participants',
  },
  ideas: {
    id: 'app.containers.Admin.projects.project.insights.shared.ideas',
    defaultMessage: 'ideas',
  },
  topics: {
    id: 'app.containers.Admin.projects.project.insights.shared.topicsCount',
    defaultMessage: 'topics',
  },
  inputs: {
    id: 'app.containers.Admin.projects.project.insights.shared.inputs',
    defaultMessage: 'inputs',
  },
  tagged: {
    id: 'app.containers.Admin.projects.project.insights.shared.tagged',
    defaultMessage: 'tagged',
  },
  topicsAutoDetected: {
    id: 'app.containers.Admin.projects.project.insights.shared.topicsAutoDetected',
    defaultMessage: 'Topics automatically generated by AI from idea content',
  },
  manualTagsCoverage: {
    id: 'app.containers.Admin.projects.project.insights.shared.manualTagsCoverage',
    defaultMessage:
      '{tagged} of {total} ideas were manually tagged by participants ({percentage}% coverage)',
  },
  noAiTopics: {
    id: 'app.containers.Admin.projects.project.insights.shared.noAiTopics',
    defaultMessage: 'No AI topics generated yet',
  },
  noManualTags: {
    id: 'app.containers.Admin.projects.project.insights.shared.noManualTags',
    defaultMessage: 'No manual tags assigned yet',
  },
  unlockAiTopicClustering: {
    id: 'app.containers.Admin.projects.project.insights.shared.unlockAiTopicClustering',
    defaultMessage: 'Unlock AI Topic Clustering',
  },
  aiTopicClusteringDescription: {
    id: 'app.containers.Admin.projects.project.insights.shared.aiTopicClusteringDescription',
    defaultMessage:
      "Automatically organize all ideas into meaningful themes, even when participants don't tag them.",
  },
  upgradeToPro: {
    id: 'app.containers.Admin.projects.project.insights.shared.upgradeToPro',
    defaultMessage: 'Upgrade to Pro',
  },
});
