import { defineMessages } from 'react-intl';

export default defineMessages({
  deletedUser: {
    id: 'app.components.UserName.deletedUser',
    defaultMessage: 'unknown author',
  },
  verified: {
    id: 'app.components.UserName.verified',
    defaultMessage: 'Verified',
  },
  anonymous: {
    id: 'app.components.UserName.anonymous',
    defaultMessage: 'Anonymous',
  },
  anonymousTooltip: {
    id: 'app.components.UserName.anonymousTooltip2',
    defaultMessage: 'This user has decided to anonymize their contribution',
  },
  authorWithNoNameTooltip: {
    id: 'app.components.UserName.authorWithNoNameTooltip',
    defaultMessage:
      'Your name has been autogenerated because you have not entered your name. Please update your profile if you would like to change it.',
  },
});
