export const LOAD_CURRENT_TENANT_REQUEST = 'utils/tenant/CURRENT_TENANT_REQUEST';
export const LOAD_CURRENT_TENANT_SUCCESS = 'utils/tenant/CURRENT_TENANT_SUCCESS';
export const LOAD_CURRENT_TENANT_ERROR = 'utils/tenant/CURRENT_TENANT_ERROR';
