export const LOAD_TOPICS_REQUEST = 'app/IdeasNewPage2/LOAD_TOPICS_REQUEST';
export const LOAD_AREAS_REQUEST = 'app/IdeasNewPage2/LOAD_AREAS_REQUEST';
export const LOAD_PROJECTS_REQUEST = 'app/IdeasNewPage2/LOAD_PROJECTS_REQUEST';
export const LOAD_TOPICS_SUCCESS = 'app/IdeasNewPage2/LOAD_TOPICS_SUCCESS';
export const LOAD_AREAS_SUCCESS = 'app/IdeasNewPage2/LOAD_AREAS_SUCCESS';
export const LOAD_PROJECTS_SUCCESS = 'app/IdeasNewPage2/LOAD_PROJECTS_SUCCESS';
