export default (_projectId) => ({
  schema: {
    type: 'object',
    properties: {
      title_multiloc: {
        type: 'object',
        minProperties: 1,
        properties: {
          en: {
            minLength: 10,
            maxLength: 80,
            type: 'string',
          },
          'nl-BE': {
            minLength: 10,
            maxLength: 80,
            type: 'string',
          },
          'fr-BE': {
            minLength: 10,
            maxLength: 80,
            type: 'string',
          },
        },
      },
      body_multiloc: {
        type: 'object',
        minLength: 3,
        minProperties: 1,
        properties: {
          en: {
            minLength: 40,
            // TODO custom validation sanitizes html before counting
            type: 'string',
          },
          'nl-BE': {
            minLength: 40,
            type: 'string',
          },
          'fr-BE': {
            minLength: 40,
            type: 'string',
          },
        },
      },
      topics: {
        type: 'array',
        items: {
          oneOf: [
            {
              id: 'b11e77b9-c58f-499c-8a72-4b75704664e8',
              attributes: {
                title_multiloc: {
                  en: 'Nature and animals',
                  mi: 'Nature and biodiversity',
                  'ar-SA': 'الطبيعة والتنوع البيولوجي',
                  'da-DK': 'Natur og biodiversitet',
                  'de-DE': 'Natur und biologische Vielfalt',
                  'en-CA': 'Nature and biodiversity',
                  'en-GB': 'Nature and biodiversity',
                  'es-CL': 'Naturaleza y biodiversidad',
                  'es-ES': 'Naturaleza y biodiversidad',
                  'fr-BE': 'Nature et biodiversité',
                  'fr-FR': 'Nature et biodiversité',
                  'hu-HU': 'Nature and biodiversity',
                  'it-IT': 'Natura e biodiversità',
                  'kl-GL':
                    'Pinngortitaq aamma uumassusillit assigiinngissitaarnerat',
                  'lb-LU': 'Nature and biodiversity',
                  'nb-NO': 'Nature and animals',
                  'nl-BE': 'Natuur en biodiversiteit',
                  'nl-NL': 'Natuur en biodiversiteit',
                  'pl-PL': 'Przyroda i różnorodność biologiczna',
                  'pt-BR': 'Natureza e biodiversidade',
                  'ro-RO': 'Natură și biodiversitate',
                  'sr-Latn': 'Priroda i biodiverzitet',
                },
                description_multiloc: {
                  en: 'Nature and animals',
                  mi: 'Nature and biodiversity',
                  'ar-SA': 'الطبيعة والتنوع البيولوجي',
                  'da-DK': 'Natur og biodiversitet',
                  'de-DE': 'Natur und biologische Vielfalt',
                  'en-CA': 'Nature and biodiversity',
                  'en-GB': 'Nature and biodiversity',
                  'es-CL': 'Naturaleza y biodiversidad',
                  'es-ES': 'Naturaleza y biodiversidad',
                  'fr-BE': 'Nature et biodiversité',
                  'fr-FR': 'Nature et biodiversité',
                  'hu-HU': 'Nature and biodiversity',
                  'it-IT': 'Natura e biodiversità',
                  'kl-GL':
                    'Pinngortitaq aamma uumassusillit assigiinngissitaarnerat',
                  'lb-LU': 'Nature and biodiversity',
                  'nb-NO': 'Nature and animals',
                  'nl-BE': 'Natuur en biodiversiteit',
                  'nl-NL': 'Natuur en biodiversiteit',
                  'pl-PL': 'Przyroda i różnorodność biologiczna',
                  'pt-BR': 'Natureza e biodiversidade',
                  'ro-RO': 'Natură și biodiversitate',
                  'sr-Latn': 'Priroda i biodiverzitet',
                },
                code: 'nature',
                ordering: 3,
                icon: null,
              },
            },
            {
              id: '10b32b83-88e1-43fc-b79f-c6d31b626439',
              attributes: {
                title_multiloc: {
                  en: 'Cleanliness and waste',
                  mi: 'Cleanliness and waste',
                  'ar-SA': 'النظافة والنفايات',
                  'da-DK': 'Renlighed og affald',
                  'de-DE': 'Sauberkeit und Abfall',
                  'en-CA': 'Cleanliness and waste',
                  'en-GB': 'Cleanliness and waste',
                  'es-CL': 'Limpieza y residuos',
                  'es-ES': 'Limpieza y residuos',
                  'fr-BE': 'Propreté et déchets',
                  'fr-FR': 'Propreté et déchets',
                  'hu-HU': 'Cleanliness and waste',
                  'it-IT': 'Pulizia e rifiuti',
                  'kl-GL': 'Avatangiiseq eqqagassallu',
                  'lb-LU': 'Cleanliness and waste',
                  'nb-NO': 'Cleanliness and waste',
                  'nl-BE': 'Netheid en afval',
                  'nl-NL': 'Netheid en afval',
                  'pl-PL': 'Czystość i odpady',
                  'pt-BR': 'Limpeza e desperdício',
                  'ro-RO': 'Curățenie și deșeuri',
                  'sr-Latn': 'Čistoća i otpad',
                },
                description_multiloc: {
                  en: 'Cleanliness and waste',
                  mi: 'Cleanliness and waste',
                  'ar-SA': 'النظافة والنفايات',
                  'da-DK': 'Renlighed og affald',
                  'de-DE': 'Sauberkeit und Abfall',
                  'en-CA': 'Cleanliness and waste',
                  'en-GB': 'Cleanliness and waste',
                  'es-CL': 'Limpieza y residuos',
                  'es-ES': 'Limpieza y residuos',
                  'fr-BE': 'Propreté et déchets',
                  'fr-FR': 'Propreté et déchets',
                  'hu-HU': 'Cleanliness and waste',
                  'it-IT': 'Pulizia e rifiuti',
                  'kl-GL': 'Avatangiiseq eqqagassallu',
                  'lb-LU': 'Cleanliness and waste',
                  'nb-NO': 'Cleanliness and waste',
                  'nl-BE': 'Netheid en afval',
                  'nl-NL': 'Netheid en afval',
                  'pl-PL': 'Czystość i odpady',
                  'pt-BR': 'Limpeza e desperdício',
                  'ro-RO': 'Curățenie și deșeuri',
                  'sr-Latn': 'Čistoća i otpad',
                },
                code: 'waste',
                ordering: 4,
                icon: null,
              },
            },
            {
              id: '0859d4c0-cacb-45db-961f-f275d0668d99',
              attributes: {
                title_multiloc: {
                  en: 'Sustainable development',
                  mi: 'Sustainable development',
                  'ar-SA': 'التنمية المستدامة',
                  'da-DK': 'Bæredygtig udvikling',
                  'de-DE': 'Nachhaltige Entwicklung',
                  'en-CA': 'Sustainable development',
                  'en-GB': 'Sustainable development',
                  'es-CL': 'Desarrollo sostenible',
                  'es-ES': 'Desarrollo sostenible',
                  'fr-BE': 'Développement durable',
                  'fr-FR': 'Développement durable',
                  'hu-HU': 'Sustainable development',
                  'it-IT': 'Sviluppo sostenibile',
                  'kl-GL':
                    'Piujuartitsinermik tunngaveqarluni ineriartortitsineq',
                  'lb-LU': 'Sustainable development',
                  'nb-NO': 'Sustainable development',
                  'nl-BE': 'Duurzame ontwikkeling',
                  'nl-NL': 'Duurzame ontwikkeling',
                  'pl-PL': 'Zrównoważony rozwój',
                  'pt-BR': 'Desenvolvimento sustentável',
                  'ro-RO': 'Dezvoltare durabilă',
                  'sr-Latn': 'Održivi razvoj',
                },
                description_multiloc: {
                  en: 'Sustainable development',
                  mi: 'Sustainable development',
                  'ar-SA': 'التنمية المستدامة',
                  'da-DK': 'Bæredygtig udvikling',
                  'de-DE': 'Nachhaltige Entwicklung',
                  'en-CA': 'Sustainable development',
                  'en-GB': 'Sustainable development',
                  'es-CL': 'Desarrollo sostenible',
                  'es-ES': 'Desarrollo sostenible',
                  'fr-BE': 'Développement durable',
                  'fr-FR': 'Développement durable',
                  'hu-HU': 'Sustainable development',
                  'it-IT': 'Sviluppo sostenibile',
                  'kl-GL':
                    'Piujuartitsinermik tunngaveqarluni ineriartortitsineq',
                  'lb-LU': 'Sustainable development',
                  'nb-NO': 'Sustainable development',
                  'nl-BE': 'Duurzame ontwikkeling',
                  'nl-NL': 'Duurzame ontwikkeling',
                  'pl-PL': 'Zrównoważony rozwój',
                  'pt-BR': 'Desenvolvimento sustentável',
                  'ro-RO': 'Dezvoltare durabilă',
                  'sr-Latn': 'Održivi razvoj',
                },
                code: 'sustainability',
                ordering: 5,
                icon: null,
              },
            },
            {
              id: 'ec9fa3b6-d943-420e-bfab-a503696fab69',
              attributes: {
                title_multiloc: {
                  en: 'Mobility',
                  mi: 'Mobility',
                  'ar-SA': 'التنقل',
                  'da-DK': 'Mobilitet',
                  'de-DE': 'Mobilität',
                  'en-CA': 'Mobility',
                  'en-GB': 'Mobility',
                  'es-CL': 'Movilidad',
                  'es-ES': 'Movilidad',
                  'fr-BE': 'Mobilité',
                  'fr-FR': 'Mobilité',
                  'hu-HU': 'Mobility',
                  'it-IT': 'Mobilità',
                  'kl-GL': 'Angallanneq',
                  'lb-LU': 'Mobility',
                  'nb-NO': 'Mobility',
                  'nl-BE': 'Mobiliteit',
                  'nl-NL': 'Mobiliteit',
                  'pl-PL': 'Mobilność',
                  'pt-BR': 'Mobilidade',
                  'ro-RO': 'Mobilitate urbană',
                  'sr-Latn': 'Mobilnost',
                },
                description_multiloc: {
                  en: 'Mobility',
                  mi: 'Mobility',
                  'ar-SA': 'التنقل',
                  'da-DK': 'Mobilitet',
                  'de-DE': 'Mobilität',
                  'en-CA': 'Mobility',
                  'en-GB': 'Mobility',
                  'es-CL': 'Movilidad',
                  'es-ES': 'Movilidad',
                  'fr-BE': 'Mobilité',
                  'fr-FR': 'Mobilité',
                  'hu-HU': 'Mobility',
                  'it-IT': 'Mobilità',
                  'kl-GL': 'Angallanneq',
                  'lb-LU': 'Mobility',
                  'nb-NO': 'Mobility',
                  'nl-BE': 'Mobiliteit',
                  'nl-NL': 'Mobiliteit',
                  'pl-PL': 'Mobilność',
                  'pt-BR': 'Mobilidade',
                  'ro-RO': 'Mobilitate urbană',
                  'sr-Latn': 'Mobilnost',
                },
                code: 'mobility',
                ordering: 6,
                icon: null,
              },
            },
            {
              id: '56fb1915-b77f-4803-80e0-f5a5972f509b',
              attributes: {
                title_multiloc: {
                  en: 'Energy and technology',
                  mi: 'Energy and technology',
                  'ar-SA': 'الطاقة والتكنولوجيا',
                  'da-DK': 'Energi og teknologi',
                  'de-DE': 'Energie und Technologie',
                  'en-CA': 'Energy and technology',
                  'en-GB': 'Energy and technology',
                  'es-CL': 'Energía y tecnología',
                  'es-ES': 'Energía y tecnología',
                  'fr-BE': 'Énergie et technologie',
                  'fr-FR': 'Énergie et technologie',
                  'hu-HU': 'Energy and technology',
                  'it-IT': 'Energia e tecnologia',
                  'kl-GL': 'Nukissiuutit aamma teknologi',
                  'lb-LU': 'Energy and technology',
                  'nb-NO': 'Energy and technology',
                  'nl-BE': 'Energie en technologie',
                  'nl-NL': 'Energie en technologie',
                  'pl-PL': 'Energia i technologia',
                  'pt-BR': 'Energia e tecnologia',
                  'ro-RO': 'Energie și tehnologie',
                  'sr-Latn': 'Energija i tehnologija',
                },
                description_multiloc: {
                  en: 'Energy and technology',
                  mi: 'Energy and technology',
                  'ar-SA': 'الطاقة والتكنولوجيا',
                  'da-DK': 'Energi og teknologi',
                  'de-DE': 'Energie und Technik',
                  'en-CA': 'Energy and technology',
                  'en-GB': 'Energy and technology',
                  'es-CL': 'Energía y tecnología',
                  'es-ES': 'Energía y tecnología',
                  'fr-BE': 'Énergie et technologie',
                  'fr-FR': 'Énergie et technologie',
                  'hu-HU': 'Energy and technology',
                  'it-IT': 'Energia e tecnologia',
                  'kl-GL': 'Nukissiuutit aamma teknologi',
                  'lb-LU': 'Energy and technology',
                  'nb-NO': 'Energy and technology',
                  'nl-BE': 'Energie en technologie',
                  'nl-NL': 'Energie en technologie',
                  'pl-PL': 'Energia i technologia',
                  'pt-BR': 'Energia e tecnologia',
                  'ro-RO': 'Energie și tehnologie',
                  'sr-Latn': 'Energija i tehnologija',
                },
                code: 'technology',
                ordering: 7,
                icon: null,
              },
            },
            {
              id: 'e1e005ce-cc24-405f-aeac-e8562126d8c7',
              attributes: {
                title_multiloc: {
                  en: 'Work, economy and tourism',
                  mi: 'Work, economy and tourism',
                  'ar-SA': 'العمل والاقتصاد والسياحة',
                  'da-DK': 'Arbejde, økonomi og turisme',
                  'de-DE': 'Arbeit, Wirtschaft und Tourismus',
                  'en-CA': 'Work, economy and tourism',
                  'en-GB': 'Work, economy and tourism',
                  'es-CL': 'Trabajo, economía y turismo',
                  'es-ES': 'Trabajo, economía y turismo',
                  'fr-BE': 'Emploi, economie et tourisme',
                  'fr-FR': 'Emploi, economie et tourisme',
                  'hu-HU': 'Work, economy and tourism',
                  'it-IT': 'Lavoro, economia e turismo',
                  'kl-GL': 'Sulineq, aningaasaqarneq takornariaqarnerlu',
                  'lb-LU': 'Work, economy and tourism',
                  'nb-NO': 'Work, economy and tourism',
                  'nl-BE': 'Werk, economie en toerisme',
                  'nl-NL': 'Werk, economie en toerisme',
                  'pl-PL': 'Praca, gospodarka i turystyka',
                  'pt-BR': 'Trabalho, economia e turismo',
                  'ro-RO': 'Muncă, economie și turism',
                  'sr-Latn': 'Posao, ekonomija i turizam',
                },
                description_multiloc: {
                  en: 'Work, economy and tourism',
                  mi: 'Work, economy and tourism',
                  'ar-SA': 'العمل والاقتصاد والسياحة',
                  'da-DK': 'Arbejde, økonomi og turisme',
                  'de-DE': 'Arbeit, Wirtschaft und Tourismus',
                  'en-CA': 'Work, economy and tourism',
                  'en-GB': 'Work, economy and tourism',
                  'es-CL': 'Trabajo, economía y turismo',
                  'es-ES': 'Trabajo, economía y turismo',
                  'fr-BE': 'Emploi, economie et tourisme',
                  'fr-FR': 'Emploi, economie et tourisme',
                  'hu-HU': 'Work, economy and tourism',
                  'it-IT': 'Lavoro, economia e turismo',
                  'kl-GL': 'Sulineq, aningaasaqarneq takornariaqarnerlu',
                  'lb-LU': 'Work, economy and tourism',
                  'nb-NO': 'Work, economy and tourism',
                  'nl-BE': 'Werk, economie en toerisme',
                  'nl-NL': 'Werk, economie en toerisme',
                  'pl-PL': 'Praca, gospodarka i turystyka',
                  'pt-BR': 'Trabalho, economia e turismo',
                  'ro-RO': 'Muncă, economie și turism',
                  'sr-Latn': 'Posao, ekonomija i turizam',
                },
                code: 'economy',
                ordering: 8,
                icon: null,
              },
            },
            {
              id: '2a83d38a-ae7a-41c1-a494-afd2d0622014',
              attributes: {
                title_multiloc: {
                  en: 'Housing',
                  mi: 'Housing',
                  'ar-SA': 'الإسكان',
                  'da-DK': 'Boliger',
                  'de-DE': 'Wohnen',
                  'en-CA': 'Housing',
                  'en-GB': 'Housing',
                  'es-CL': 'Vivienda',
                  'es-ES': 'Vivienda',
                  'fr-BE': 'Logement',
                  'fr-FR': 'Logement',
                  'hu-HU': 'Housing',
                  'it-IT': 'Housing',
                  'kl-GL': 'Inissiat',
                  'lb-LU': 'Housing',
                  'nb-NO': 'Housing',
                  'nl-BE': 'Wonen',
                  'nl-NL': 'Wonen',
                  'pl-PL': 'Mieszkalnictwo',
                  'pt-BR': 'Moradia',
                  'ro-RO': 'Locuințe',
                  'sr-Latn': 'Stanovanje',
                },
                description_multiloc: {
                  en: 'Housing',
                  mi: 'Housing',
                  'ar-SA': 'الإسكان',
                  'da-DK': 'Boliger',
                  'de-DE': 'Wohnen',
                  'en-CA': 'Housing',
                  'en-GB': 'Housing',
                  'es-CL': 'Vivienda',
                  'es-ES': 'Vivienda',
                  'fr-BE': 'Logement',
                  'fr-FR': 'Logement',
                  'hu-HU': 'Housing',
                  'it-IT': 'Housing',
                  'kl-GL': 'Inissiat',
                  'lb-LU': 'Housing',
                  'nb-NO': 'Housing',
                  'nl-BE': 'Wonen',
                  'nl-NL': 'Wonen',
                  'pl-PL': 'Mieszkalnictwo',
                  'pt-BR': 'Moradia',
                  'ro-RO': 'Locuințe',
                  'sr-Latn': 'Stanovanje',
                },
                code: 'housing',
                ordering: 9,
                icon: null,
              },
            },
            {
              id: '6dafcdd8-e381-4117-914e-c8c7da5474cd',
              attributes: {
                title_multiloc: {
                  en: 'Public spaces and buildings',
                  mi: 'Public spaces and buildings',
                  'ar-SA': 'المساحات والمباني العامة',
                  'da-DK': 'Offentlige rum og bygninger',
                  'de-DE': 'Öffentliche Räume und Gebäude',
                  'en-CA': 'Public spaces and buildings',
                  'en-GB': 'Public spaces and buildings',
                  'es-CL': 'Espacios públicos y edificios',
                  'es-ES': 'Espacios públicos y edificios',
                  'fr-BE': 'Espaces et bâtiments publics',
                  'fr-FR': 'Espaces publics et bâti',
                  'hu-HU': 'Public spaces and buildings',
                  'it-IT': 'Spazi pubblici ed edifici',
                  'kl-GL': 'Tamanit ornigarneqartut illullu',
                  'lb-LU': 'Public spaces and buildings',
                  'nb-NO': 'Public spaces and buildings',
                  'nl-BE': 'Openbare ruimtes en gebouwen',
                  'nl-NL': 'Openbare ruimtes en gebouwen',
                  'pl-PL': 'Przestrzeń publiczna i budynki',
                  'pt-BR': 'Construções e espaços públicos',
                  'ro-RO': 'Spații publice și clădiri',
                  'sr-Latn': 'Javni prostori i zgrade',
                },
                description_multiloc: {
                  en: 'Public spaces and buildings',
                  mi: 'Public spaces and buildings',
                  'ar-SA': 'المساحات والمباني العامة',
                  'da-DK': 'Offentlige rum og bygninger',
                  'de-DE': 'Öffentliche Räume und Gebäude',
                  'en-CA': 'Public spaces and buildings',
                  'en-GB': 'Public spaces and buildings',
                  'es-CL': 'Espacios públicos y edificios',
                  'es-ES': 'Espacios públicos y edificios',
                  'fr-BE': 'Espaces et bâtiments publics',
                  'fr-FR': 'Espaces publics et bâti',
                  'hu-HU': 'Public spaces and buildings',
                  'it-IT': 'Spazi pubblici ed edifici',
                  'kl-GL': 'Tamanit ornigarneqartut illullu',
                  'lb-LU': 'Public spaces and buildings',
                  'nb-NO': 'Public spaces and buildings',
                  'nl-BE': 'Openbare ruimtes en gebouwen',
                  'nl-NL': 'Openbare ruimtes en gebouwen',
                  'pl-PL': 'Przestrzeń publiczna i budynki',
                  'pt-BR': 'Construções e espaços públicos',
                  'ro-RO': 'Spații publice și clădiri',
                  'sr-Latn': 'Javni prostori i zgrade',
                },
                code: 'public_space',
                ordering: 10,
                icon: null,
              },
            },
            {
              id: '238f3c18-8cec-4009-a859-55f608d03293',
              attributes: {
                title_multiloc: {
                  en: 'Safety',
                  mi: 'Safety',
                  'ar-SA': 'السلامة',
                  'da-DK': 'Sikkerhed',
                  'de-DE': 'Sicherheit',
                  'en-CA': 'Safety',
                  'en-GB': 'Safety',
                  'es-CL': 'Seguridad',
                  'es-ES': 'Seguridad',
                  'fr-BE': 'Sécurité',
                  'fr-FR': 'Sécurité',
                  'hu-HU': 'Safety',
                  'it-IT': 'Sicurezza',
                  'kl-GL': 'Isumannaallisaaneq',
                  'lb-LU': 'Safety',
                  'nb-NO': 'Safety',
                  'nl-BE': 'Veiligheid',
                  'nl-NL': 'Veiligheid',
                  'pl-PL': 'Bezpieczeństwo',
                  'pt-BR': 'Segurança',
                  'ro-RO': 'Securitate',
                  'sr-Latn': 'Sigurnost',
                },
                description_multiloc: {
                  en: 'Safety',
                  mi: 'Safety',
                  'ar-SA': 'السلامة',
                  'da-DK': 'Sikkerhed',
                  'de-DE': 'Sicherheit',
                  'en-CA': 'Safety',
                  'en-GB': 'Safety',
                  'es-CL': 'Seguridad',
                  'es-ES': 'Seguridad',
                  'fr-BE': 'Sécurité',
                  'fr-FR': 'Sécurité',
                  'hu-HU': 'Safety',
                  'it-IT': 'Sicurezza',
                  'kl-GL': 'Isumannaallisaaneq',
                  'lb-LU': 'Safety',
                  'nb-NO': 'Safety',
                  'nl-BE': 'Veiligheid',
                  'nl-NL': 'Veiligheid',
                  'pl-PL': 'Bezpieczeństwo',
                  'pt-BR': 'Segurança',
                  'ro-RO': 'Securitate',
                  'sr-Latn': 'Sigurnost',
                },
                code: 'safety',
                ordering: 11,
                icon: null,
              },
            },
            {
              id: '21946196-505a-4b75-98b3-158b29308909',
              attributes: {
                title_multiloc: {
                  en: 'Education and youth',
                  mi: 'Education and youth',
                  'ar-SA': 'التعليم والشباب',
                  'da-DK': 'Uddannelse og ungdom',
                  'de-DE': 'Bildung und Jugend',
                  'en-CA': 'Education and youth',
                  'en-GB': 'Education and youth',
                  'es-CL': 'Educación y juventud',
                  'es-ES': 'Educación y juventud',
                  'fr-BE': 'Éducation et jeunesse',
                  'fr-FR': 'Éducation et jeunesse',
                  'hu-HU': 'Education and youth',
                  'it-IT': 'Educazione e gioventù',
                  'kl-GL': 'Ilinniartitaaneq inuusuttullu',
                  'lb-LU': 'Education and youth',
                  'nb-NO': 'Education and youth',
                  'nl-BE': 'Onderwijs en jeugd',
                  'nl-NL': 'Onderwijs en jeugd',
                  'pl-PL': 'Edukacja i młodzież',
                  'pt-BR': 'Educação e juventude',
                  'ro-RO': 'Educație și tineret',
                  'sr-Latn': 'Obrazovanje i omladina',
                },
                description_multiloc: {
                  en: 'Education and youth',
                  mi: 'Education and youth',
                  'ar-SA': 'التعليم والشباب',
                  'da-DK': 'Uddannelse og ungdom',
                  'de-DE': 'Bildung und Jugend',
                  'en-CA': 'Education and youth',
                  'en-GB': 'Education and youth',
                  'es-CL': 'Educación y juventud',
                  'es-ES': 'Educación y juventud',
                  'fr-BE': 'Éducation et jeunesse',
                  'fr-FR': 'Éducation et jeunesse',
                  'hu-HU': 'Education and youth',
                  'it-IT': 'Educazione e gioventù',
                  'kl-GL': 'Ilinniartitaaneq inuusuttullu',
                  'lb-LU': 'Education and youth',
                  'nb-NO': 'Education and youth',
                  'nl-BE': 'Onderwijs en jeugd',
                  'nl-NL': 'Onderwijs en jeugd',
                  'pl-PL': 'Edukacja i młodzież',
                  'pt-BR': 'Educação e juventude',
                  'ro-RO': 'Educație și tineret',
                  'sr-Latn': 'Obrazovanje i omladina',
                },
                code: 'education',
                ordering: 12,
                icon: null,
              },
            },
            {
              id: 'd7bb141e-5840-4724-81e6-e2781997db1d',
              attributes: {
                title_multiloc: {
                  en: 'Culture, sports and events',
                  mi: 'Culture, sports and events',
                  'ar-SA': 'الثقافة والرياضة والفعاليات',
                  'da-DK': 'Kultur, idræt og arrangementer',
                  'de-DE': 'Kultur, Sport und Veranstaltungen',
                  'en-CA': 'Culture, sports and events',
                  'en-GB': 'Culture, sports and events',
                  'es-CL': 'Cultura, deportes y eventos',
                  'es-ES': 'Cultura, deportes y eventos',
                  'fr-BE': 'Culture, sports et événements',
                  'fr-FR': 'Culture, sports et événements',
                  'hu-HU': 'Culture, sports and events',
                  'it-IT': 'Cultura, sport ed eventi',
                  'kl-GL': 'Kulturi, timersorneq aaqqissuussinerillu',
                  'lb-LU': 'Culture, sports and events',
                  'nb-NO': 'Culture, sports and events',
                  'nl-BE': 'Cultuur, sport en evenementen',
                  'nl-NL': 'Cultuur, sport en evenementen',
                  'pl-PL': 'Kultura, sport i wydarzenia',
                  'pt-BR': 'Cultura, esportes e eventos',
                  'ro-RO': 'Cultură, sport și evenimente',
                  'sr-Latn': 'Kultura, sport i događaji',
                },
                description_multiloc: {
                  en: 'Culture, sports and events',
                  mi: 'Culture, sports and events',
                  'ar-SA': 'الثقافة والرياضة والفعاليات',
                  'da-DK': 'Kultur, idræt og arrangementer',
                  'de-DE': 'Kultur, Sport und Veranstaltungen',
                  'en-CA': 'Culture, sports and events',
                  'en-GB': 'Culture, sports and events',
                  'es-CL': 'Cultura, deportes y eventos',
                  'es-ES': 'Cultura, deportes y eventos',
                  'fr-BE': 'Culture, sports et événements',
                  'fr-FR': 'Culture, sports et événements',
                  'hu-HU': 'Culture, sports and events',
                  'it-IT': 'Cultura, sport ed eventi',
                  'kl-GL': 'Kulturi, timersorneq aaqqissuussinerillu',
                  'lb-LU': 'Culture, sports and events',
                  'nb-NO': 'Culture, sports and events',
                  'nl-BE': 'Cultuur, sport en evenementen',
                  'nl-NL': 'Cultuur, sport en evenementen',
                  'pl-PL': 'Kultura, sport i wydarzenia',
                  'pt-BR': 'Cultura, esportes e eventos',
                  'ro-RO': 'Cultură, sport și evenimente',
                  'sr-Latn': 'Kultura, sport i događaji',
                },
                code: 'culture',
                ordering: 13,
                icon: null,
              },
            },
            {
              id: 'adb5bd7e-e600-4aac-ab83-7434fcc58074',
              attributes: {
                title_multiloc: {
                  en: 'Health and welfare',
                  mi: 'Health and welfare',
                  'ar-SA': 'الصحة والرعاية',
                  'da-DK': 'Helse og velfærd',
                  'de-DE': 'Gesundheit und Wohlbefinden',
                  'en-CA': 'Health and welfare',
                  'en-GB': 'Health and welfare',
                  'es-CL': 'Salud y bienestar',
                  'es-ES': 'Salud y bienestar',
                  'fr-BE': 'Santé et bien-être',
                  'fr-FR': 'Santé et bien-être',
                  'hu-HU': 'Health and welfare',
                  'it-IT': 'Salute e benessere',
                  'kl-GL': 'Peqqinnissaq atugarissaarnerlu',
                  'lb-LU': 'Health and welfare',
                  'nb-NO': 'Health and welfare',
                  'nl-BE': 'Gezondheid en welzijn',
                  'nl-NL': 'Gezondheid en welzijn',
                  'pl-PL': 'Zdrowie i opieka',
                  'pt-BR': 'Saúde e bem-estar',
                  'ro-RO': 'Sănătate și bunăstare',
                  'sr-Latn': 'Zdravlje i dobrobit',
                },
                description_multiloc: {
                  en: 'Health and welfare',
                  mi: 'Health and welfare',
                  'ar-SA': 'الصحة والرعاية',
                  'da-DK': 'Helse og velfærd',
                  'de-DE': 'Gesundheit und Wohlbefinden',
                  'en-CA': 'Health and welfare',
                  'en-GB': 'Health and welfare',
                  'es-CL': 'Salud y bienestar',
                  'es-ES': 'Salud y bienestar',
                  'fr-BE': 'Santé et bien-être',
                  'fr-FR': 'Santé et bien-être',
                  'hu-HU': 'Health and welfare',
                  'it-IT': 'Salute e benessere',
                  'kl-GL': 'Peqqinnissaq atugarissaarnerlu',
                  'lb-LU': 'Health and welfare',
                  'nb-NO': 'Health and welfare',
                  'nl-BE': 'Gezondheid en welzijn',
                  'nl-NL': 'Gezondheid en welzijn',
                  'pl-PL': 'Zdrowie i opieka',
                  'pt-BR': 'Saúde e bem-estar',
                  'ro-RO': 'Sănătate și bunăstare',
                  'sr-Latn': 'Zdravlje i dobrobit',
                },
                code: 'health',
                ordering: 14,
                icon: null,
              },
            },
            {
              id: 'e028f4f4-b685-419f-8af6-b19f31ef3370',
              attributes: {
                title_multiloc: {
                  en: 'Social inclusion',
                  mi: 'Social inclusion',
                  'ar-SA': 'الإدماج الاجتماعي',
                  'da-DK': 'Social inklusion',
                  'de-DE': 'Soziale Inklusion',
                  'en-CA': 'Social inclusion',
                  'en-GB': 'Social inclusion',
                  'es-CL': 'Inclusión social',
                  'es-ES': 'Inclusión social',
                  'fr-BE': 'Social',
                  'fr-FR': 'Social',
                  'hu-HU': 'Social inclusion',
                  'it-IT': 'Inclusione sociale',
                  'kl-GL': 'Akuutitsineq',
                  'lb-LU': 'Social inclusion',
                  'nb-NO': 'Social inclusion',
                  'nl-BE': 'Sociale inclusie',
                  'nl-NL': 'Sociale inclusie',
                  'pl-PL': 'Integracja społeczna',
                  'pt-BR': 'Inclusão social',
                  'ro-RO': 'Incluziune socială',
                  'sr-Latn': 'Socijalna inkluzija',
                },
                description_multiloc: {
                  en: 'Social inclusion',
                  mi: 'Social inclusion',
                  'ar-SA': 'الإدماج الاجتماعي',
                  'da-DK': 'Social inklusion',
                  'de-DE': 'Soziale Inklusion',
                  'en-CA': 'Social inclusion',
                  'en-GB': 'Social inclusion',
                  'es-CL': 'Inclusión social',
                  'es-ES': 'Inclusión social',
                  'fr-BE': 'Social',
                  'fr-FR': 'Social',
                  'hu-HU': 'Social inclusion',
                  'it-IT': 'Inclusione sociale',
                  'kl-GL': 'Akuutitsineq',
                  'lb-LU': 'Social inclusion',
                  'nb-NO': 'Social inclusion',
                  'nl-BE': 'Sociale inclusie',
                  'nl-NL': 'Sociale inclusie',
                  'pl-PL': 'Integracja społeczna',
                  'pt-BR': 'Inclusão social',
                  'ro-RO': 'Incluziune socială',
                  'sr-Latn': 'Socijalna inkluzija',
                },
                code: 'inclusion',
                ordering: 15,
                icon: null,
              },
            },
            {
              id: '78d3ecab-2160-4d42-b411-631fdb449585',
              attributes: {
                title_multiloc: {
                  en: 'Community development',
                  mi: 'Community development',
                  'ar-SA': 'تنمية المجتمع',
                  'da-DK': 'Udvikling af lokale fællesskaber',
                  'de-DE': 'Entwicklung der Gemeinschaft',
                  'en-CA': 'Community development',
                  'en-GB': 'Community development',
                  'es-CL': 'Desarrollo comunitario',
                  'es-ES': 'Desarrollo comunitario',
                  'fr-BE': 'Développement communautaire',
                  'fr-FR': 'Développement communautaire',
                  'hu-HU': 'Community development',
                  'it-IT': 'Sviluppo comunitario',
                  'kl-GL': 'Najukkamik ineriartortitsineq',
                  'lb-LU': 'Community development',
                  'nb-NO': 'Community development',
                  'nl-BE': 'Ontwikkeling gemeenschap',
                  'nl-NL': 'Ontwikkeling gemeenschap',
                  'pl-PL': 'Rozwój lokalny',
                  'pt-BR': 'Desenvolvimento da comunidade',
                  'ro-RO': 'Dezvoltare comunitară',
                  'sr-Latn': 'Razvoj zajednice',
                },
                description_multiloc: {
                  en: 'Community development',
                  mi: 'Community development',
                  'ar-SA': 'تنمية المجتمع',
                  'da-DK': 'Udvikling af lokale fællesskaber',
                  'de-DE': 'Entwicklung der Gemeinschaft',
                  'en-CA': 'Community development',
                  'en-GB': 'Community development',
                  'es-CL': 'Desarrollo comunitario',
                  'es-ES': 'Desarrollo comunitario',
                  'fr-BE': 'Développement communautaire',
                  'fr-FR': 'Développement communautaire',
                  'hu-HU': 'Community development',
                  'it-IT': 'Sviluppo comunitario',
                  'kl-GL': 'Najukkamik ineriartortitsineq',
                  'lb-LU': 'Community development',
                  'nb-NO': 'Community development',
                  'nl-BE': 'Ontwikkeling gemeenschap',
                  'nl-NL': 'Ontwikkeling gemeenschap',
                  'pl-PL': 'Rozwój lokalny',
                  'pt-BR': 'Desenvolvimento da comunidade',
                  'ro-RO': 'Dezvoltare comunitară',
                  'sr-Latn': 'Razvoj zajednice',
                },
                code: 'community',
                ordering: 16,
                icon: null,
              },
            },
            {
              id: '08cb3fb6-fea9-40ca-8aea-e91c431a8d7f',
              attributes: {
                title_multiloc: {
                  en: 'Public services',
                  mi: 'Public services',
                  'ar-SA': 'الخدمات العامة',
                  'da-DK': 'Offentlige tjenester',
                  'de-DE': 'Öffentliche Dienste',
                  'en-CA': 'Public services',
                  'en-GB': 'Public services',
                  'es-CL': 'Servicio público',
                  'es-ES': 'Servicios públicos',
                  'fr-BE': 'Services publics',
                  'fr-FR': 'Services publics',
                  'hu-HU': 'Public services',
                  'it-IT': 'Servizi pubblici',
                  'kl-GL': 'Pisortat kiffartuussinerat',
                  'lb-LU': 'Public services',
                  'nb-NO': 'Public services',
                  'nl-BE': 'Openbare diensten',
                  'nl-NL': 'Openbare diensten',
                  'pl-PL': 'Usługi publiczne',
                  'pt-BR': 'Serviços públicos',
                  'ro-RO': 'Servicii publice',
                  'sr-Latn': 'Javne službe',
                },
                description_multiloc: {
                  en: 'Public services',
                  mi: 'Public services',
                  'ar-SA': 'الخدمات العامة',
                  'da-DK': 'Offentlige tjenester',
                  'de-DE': 'Öffentliche Dienste',
                  'en-CA': 'Public services',
                  'en-GB': 'Public services',
                  'es-CL': 'Servicio público',
                  'es-ES': 'Servicios públicos',
                  'fr-BE': 'Services publics',
                  'fr-FR': 'Services publics',
                  'hu-HU': 'Public services',
                  'it-IT': 'Servizi pubblici',
                  'kl-GL': 'Pisortat kiffartuussinerat',
                  'lb-LU': 'Public services',
                  'nb-NO': 'Public services',
                  'nl-BE': 'Openbare diensten',
                  'nl-NL': 'Openbare diensten',
                  'pl-PL': 'Usługi publiczne',
                  'pt-BR': 'Serviços públicos',
                  'ro-RO': 'Servicii publice',
                  'sr-Latn': 'Javne službe',
                },
                code: 'services',
                ordering: 17,
                icon: null,
              },
            },
            {
              id: 'a7d3721d-3569-4bec-9f11-e234490333b2',
              attributes: {
                title_multiloc: {
                  en: 'Other',
                  mi: 'Other',
                  'ar-SA': 'آخر',
                  'da-DK': 'Andet',
                  'de-DE': 'Andere',
                  'en-CA': 'Other',
                  'en-GB': 'Other',
                  'es-CL': 'Otros',
                  'es-ES': 'Otros',
                  'fr-BE': 'Autres',
                  'fr-FR': 'Autres',
                  'hu-HU': 'Other',
                  'it-IT': 'Altro',
                  'kl-GL': 'Allat',
                  'lb-LU': 'Other',
                  'nb-NO': 'Other',
                  'nl-BE': 'Overige',
                  'nl-NL': 'Overige',
                  'pl-PL': 'Inny',
                  'pt-BR': 'Outros',
                  'ro-RO': 'Alte',
                  'sr-Latn': 'Drugo',
                },
                description_multiloc: {
                  en: 'Other',
                  mi: 'Other',
                  'ar-SA': 'آخر',
                  'da-DK': 'Andet',
                  'de-DE': 'Andere',
                  'en-CA': 'Other',
                  'en-GB': 'Other',
                  'es-CL': 'Otros',
                  'es-ES': 'Otros',
                  'fr-BE': 'Autres',
                  'fr-FR': 'Autres',
                  'hu-HU': 'Other',
                  'it-IT': 'Altro',
                  'kl-GL': 'Allat',
                  'lb-LU': 'Other',
                  'nb-NO': 'Other',
                  'nl-BE': 'Overige',
                  'nl-NL': 'Overige',
                  'pl-PL': 'Inny',
                  'pt-BR': 'Outros',
                  'ro-RO': 'Alte',
                  'sr-Latn': 'Drugo',
                },
                code: 'other',
                ordering: 18,
                icon: null,
              },
            },
          ],
        },
      },
    },
    required: ['title_multiloc', 'body_multiloc'],
  },
  uiSchema: {
    type: 'Categorization',
    options: {
      submit: 'ButtonBar',
      formId: 'ideaForm',
    },
    elements: [
      {
        type: 'Category',
        label: "What's your idea ?",
        elements: [
          {
            type: 'VerticalLayout',
            render: 'multiloc',
            label: 'Title',
            elements: [
              {
                type: 'Control',
                locale: 'en',
                scope: '#/properties/title_multiloc/properties/en',
              },
              {
                type: 'Control',
                locale: 'nl-BE',
                scope: '#/properties/title_multiloc/properties/nl-BE',
              },
              {
                type: 'Control',
                locale: 'fr-BE',
                scope: '#/properties/title_multiloc/properties/fr-BE',
              },
            ],
          },
          {
            type: 'VerticalLayout',
            render: 'multiloc',
            label: 'Description',
            elements: [
              {
                type: 'Control',
                render: 'WYSIWYG',
                locale: 'en',
                scope: '#/properties/body_multiloc/properties/en',
              },
              {
                type: 'Control',
                render: 'WYSIWYG',
                locale: 'nl-BE',
                scope: '#/properties/body_multiloc/properties/nl-BE',
              },
              {
                type: 'Control',
                render: 'WYSIWYG',
                locale: 'fr-BE',
                scope: '#/properties/body_multiloc/properties/fr-BE',
              },
            ],
          },
        ],
      },
      {
        type: 'Category',
        label: 'Details',
        elements: [
          {
            type: 'Control',
            scope: '#/properties/topics',
          },
        ],
      },
    ],
  },
});
