inherit_from:
  './.rubocop.yml'

AllCops:
  Include:
  <% `git status --porcelain`.lines.grep(/^[\s|!][^D]/).each do |path| %>
    - <%= path.sub(/^( M|!!) /, '') %>
  <% end %>
  Exclude:
  - '**/.*.*'
  - '**/bin/**/*'
