require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  AutoCorrect: false
  Exclude:
  - 'db/schema.rb'
  - '**/.*.*'
  - '**/bin/**/*'

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'shared_examples']
  Enabled: true
  Exclude:
  - '**/spec/**/*'
  - 'db/migrate/**/*'
  # Max: 25
Metrics/MethodLength:
  Enabled: true
  Exclude:
  - 'db/migrate/**/*'
  # Max: 10
Metrics/ClassLength:
  Enabled: true
  # Max: 100
Layout/LineLength:
  Enabled: true
  # Max: 120
Rails/LexicallyScopedActionFilter:
  Enabled: true
Style/Documentation:
  Enabled: true
  Exclude:
  - 'db/migrate/**/*'
Style/FrozenStringLiteralComment:
  AutoCorrect: true
Style/SymbolArray:
  AutoCorrect: true
Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
RSpec/DescribeClass:
  Exclude:
  - '**/spec/acceptance/**/*'
  - '**/spec/lint/**/*'
