files:
  - source: /front/app/translations/en.json
    translation: /front/app/translations/%locale%.json
    languages_mapping:
      locale:
        en: en
        "no": nb-NO
    update_option: update_without_changes
  - source: /back/config/locales/en.yml
    translation: /back/config/locales/%locale%.yml
    update_option: update_without_changes
    languages_mapping:
      locale:
        en: en
        "no": nb-NO
  - source: /back/engines/free/email_campaigns/config/locales/en.yml
    translation: /back/engines/free/email_campaigns/config/locales/%locale%.yml
    update_option: update_without_changes
    languages_mapping:
      locale:
        en: en
        "no": nb-NO
