version: '3.5'

services:
  postgres:
    image: 'camptocamp/postgres:9.6'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  web:
    container_name: cl2-back-web
    depends_on:
      - 'postgres'
      - 'redis'
      - 'mailcatcher'
      - 'rabbitmq'
    build: .
    image: citizenlabdotco/cl2-back:latest
    ports:
      - '4000:4000'
    volumes:
      - '.:/cl2_back'
    env_file:
      - '.env'
    tty: true
    stdin_open: true

  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
      - 'rabbitmq'
    build: .
    image: citizenlabdotco/cl2-back:latest
    command: sidekiq -C config/sidekiq.yml.erb
    volumes:
      - '.:/cl2_back'
    env_file:
      - '.env'
    tty: true
    stdin_open: true

  rabbitmq:
    image: 'rabbitmq:3.7-alpine'
    hostname: cl2-rabbit

  mailcatcher:
    image: 'schickling/mailcatcher'
    ports:
      - '1080:1080'

volumes:
  redis:
  postgres:

networks:
  default:
    name: cl2-back
