# Compare list of tenants I have deletd recently with list in CSV file, and
# mark those that are in CSV file as deleted.
# Also remove duplicate ID value entry.

require 'csv'

table = CSV.parse(File.read('tenants_responses.csv'), headers: true)

deleted = [
  'undp-jordan-trial.citizenlab.co',
  'dksuper.citizenlab.co',
  'spl-demo.citizenlab.co',
  'wb-demo.citizenlab.co',
  'demo-ieper.citizenlab.co',
  'stadtwien-demo.citizenlab.co',
  'landkreis-hof.citizenlab.co',
  'yasmina-demo.citizenlab.co',
  'luciana-demo.citizenlab.co',
  'andre-demo.citizenlab.co',
  'sarah-demo.citizenlab.co',
  'madeleine-demo.citizenlab.co',
  'daphne-demo.citizenlab.co',
  'gregoire-demo.citizenlab.co',
  'isobel-demo.citizenlab.co',
  'goettingen-demo.citizenlab.co',
  'vlaamseverenigingen.citizenlab.co',
  'demo-rabi.citizenlab.co',
  'amanda-demo.citizenlab.co',
  'cl-fr10.demo.citizenlab.co',
  'utrecht.demo.citizenlab.co',
  'clairedemo.citizenlab.co',
  'gemeentedordrecht.demo.citizenlab.co',
  'gemeentemaassluis.demo.citizenlab.co',
  'dankeanetest.citizenlab.co',
  'vlissingen.demo.citizenlab.co',
  'kevin2.demo.citizenlab.co',
  'goes.demo.citizenlab.co',
  'dordrecht.demo.citizenlab.co',
  'vlaanderen.demo.citizenlab.co',
  'leidenpilot.stg.citizenlab.co',
  'oegstgeest.demo.citizenlab.co',
  'guetersloh-demo.citizenlab.co',
  'istanbul-trial.citizenlab.co',
  'particitiz-trial.citizenlab.co',
  'folkinitiativ-trial.citizenlab.co',
  'magellan-society-trial.citizenlab.co',
  'slrd-trial.citizenlab.co',
  'qmmunis.citizenlab.co',
  'joburg-trial.citizenlab.co',
  'weho-demo.citizenlab.co',
  'southstormont.citizenlab.co',
  'dreamocracy-trial.citizenlab.co',
  'cityofdenton-trial.citizenlab.co',
  'saint-hubert.stg.citizenlab.co',
  'evergem.stg.citizenlab.co',
  'jd-pantanal.citizenlab.co',
  'test-idea-custom-fields.demo.citizenlab.co',
  'trial-ro-was-template.citizenlab.co',
  'trial-pl.template.citizenlab.co',
  'trial-pt-was-template.citizenlab.co',
  'jaiba1-demo.citizenlab.co',
  'escazuparticipa.citizenlab.co',
  'puertovaras.citizenlab.co',
  'neuquenparticipa.citizenlab.co',
  'fortalezacruzada.citizenlab.co',
  'somoschoapa.citizenlab.co',
  'lautaroparticipa.citizenlab.co',
  'argentinaparticipa.citizenlab.co',
  'colegioelectoral.citizenlab.co',
  'demominsal.citizenlab.co',
  'mintransporte.citizenlab.co',
  'goreantofagastademo.citizenlab.co',
  'demomimunicipio.citizenlab.co',
  'lareinaparticipa.citizenlab.co',
  'gobiernodigital.citizenlab.co',
  'demoacciona.citizenlab.co',
  'demomaipuparticipa.citizenlab.co',
  'plataformasoporte.citizenlab.co',
  'demoislademaipo.citizenlab.co',
  'municolinademo.citizenlab.co',
  'estrategiaregionaldesarrollomaule.citizenlab.co',
  'demoreformatributaria.citizenlab.co',
  'democontraloria.citizenlab.co',
  'demomuninatales.citizenlab.co',
  'democolbun.citizenlab.co',
  'democauquenes.citizenlab.co',
  'tenemosquehablardechile.citizenlab.co',
  'demoaguazul.citizenlab.co',
  'valparaisoparticipa.citizenlab.co',
  'elnuevotrato.citizenlab.co',
  'demoestacioncentral.citizenlab.co',
  'municipiodeyopal.citizenlab.co',
  'municerronaviademo.citizenlab.co',
  'demoprovidencia.citizenlab.co',
  'outthereartsdemo.citizenlab.co',
  'brent-council.citizenlab.co',
  'nursing-midwifery-council-trial.citizenlab.co',
  'bank-of-england-trial.citizenlab.co',
  'alfordtrial.citizenlab.co',
  'grandbequest.citizenlab.co',
  'fctrial.citizenlab.co',
  'publicio-test.citizenlab.co',
  'wcc-trial.citizenlab.co',
  'manchester-climate-change-trial.citizenlab.co',
  'uk-client-event.citizenlab.co',
  'notting-hill-genesis.citizenlab.co',
  'cork-trial.citizenlab.co',
  'bsi-pen-test.citizenlab.co',
  'uktest2.citizenlab.co',
  'qa-assignment.citizenlab.co',
  'koentestfail4.citizenlab.co',
  'projecttemplates.citizenlab.co',
  'greencity-one.citizenlab.co',
  'litterville-two.citizenlab.co',
  'railtown-two.citizenlab.co',
  'litterville-one.citizenlab.co',
  'caddick-consultation-demo.citizenlab.co',
  'greencity-two.citizenlab.co',
  'railtown-one.citizenlab.co',
  'iquiqueparticipa.citizenlab.co',
  'calamaparticipa.citizenlab.co',
  'constitucionparticipa.citizenlab.co',
  'aot.demo.citizenlab.co',
  'yourneweuparliament.demo.citizenlab.co',
  'wortegempetegem.demo.citizenlab.co',
  'seneffe.demo.citizenlab.co',
  'etterbeek-demo.citizenlab.co',
  'vivrelaville.demo.citizenlab.co',
  'voeubase.demo.citizenlab.co',
  'internationalsinbrussels.demo.citizenlab.co',
  'saintgilles.demo.citizenlab.co',
  'roeselareburgerbegroting.demo.citizenlab.co',
  'tubize.demo.citizenlab.co',
  'studiodada.demo.citizenlab.co',
  'ngo.template.citizenlab.co',
  'poznan.demo.citizenlab.co',
  'niepolomice.demo.citizenlab.co',
  'dg.demo.citizenlab.co'
]

File.open('tenants_responses_v2.csv', 'w') do |f|
  f << "ID,Host,Lifecycle Stage,Created At,Response,Deleted?\n"
  table.by_row.each do |row|
    if deleted.include?(row[1])
      f << "#{row[0]},#{row[1]},#{row[2]},#{row[3]},#{row[5]},tenant deleted 01-04/12/23\n"
    else
      f << "#{row[0]},#{row[1]},#{row[2]},#{row[3]},#{row[5]}\n"
    end
  end
end
