# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in analytics.gemspec.
gemspec

gem 'scenic'

group :development do
  # gem 'sqlite3'
end

# To use a debugger
# gem 'byebug', group: [:development, :test]
