/**
 * Files that still import `moment` / `moment-timezone`, exempt from the
 * no-moment ESLint rule until they are migrated to `utils/dateFormat`.
 *
 * This list is the migration's to-do list: it only ever shrinks. When you
 * convert a file, delete its line. When it reaches the characterization tests
 * (which compare against moment on purpose and stay forever), the migration is
 * done and the rule can move into the base config.
 *
 * See app/utils/dateFormat.README.md for how to convert a call.
 */
module.exports = [
  'app/api/survey_results/utils.ts',
  // Dynamic `import('moment/dist/locale/xx')` in localeGetter — no static
  // import, so it is only caught by the no-restricted-syntax rule. Grep for
  // "from 'moment" will not find it; don't prune this line automatically.
  'app/containers/App/constants.ts',
  'app/components/EventPreviews/index.tsx',
  'app/components/ParticipationCTABars/EventsCTABar/index.tsx',
  'app/components/ProjectCard/index.tsx',
  'app/components/admin/ContentBuilder/LanguageProvider/index.tsx',
  'app/components/admin/Email/DraftCampaignRow.tsx',
  'app/components/admin/Email/Scheduling/ScheduleModal.tsx',
  'app/components/admin/Email/SentCampaignRow.tsx',
  'app/components/admin/FormResults/FormResultsQuestion/MappingQuestions/components/ExportGeoJSONButton.tsx',
  'app/components/admin/FormResults/FormResultsQuestion/TextQuestion/Analysis/utils.ts',
  'app/components/admin/GraphCards/CommentsByTimeCard/generateEmptyData.ts',
  'app/components/admin/GraphCards/CommentsByTimeCard/useCommentsByTime/parse.ts',
  'app/components/admin/GraphCards/InputsByTimeCard/generateEmptyData.ts',
  'app/components/admin/GraphCards/InputsByTimeCard/useInputsByTime/parse.ts',
  'app/components/admin/GraphCards/InternalAdoptionCard/generateEmptyData.ts',
  'app/components/admin/GraphCards/InternalAdoptionCard/typings.ts',
  'app/components/admin/GraphCards/InternalAdoptionCard/useInternalAdoption/parse.ts',
  'app/components/admin/GraphCards/ParticipantsCard/generateEmptyData.ts',
  'app/components/admin/GraphCards/ParticipantsCard/useParticipants/parse.test.ts',
  'app/components/admin/GraphCards/ParticipantsCard/useParticipants/parse.ts',
  'app/components/admin/GraphCards/ReactionsByTimeCard/generateEmptyData.ts',
  'app/components/admin/GraphCards/ReactionsByTimeCard/useReactionsByTime/parse.ts',
  'app/components/admin/GraphCards/RegistrationsCard/generateEmptyData.ts',
  'app/components/admin/GraphCards/RegistrationsCard/useRegistrations/parse.test.ts',
  'app/components/admin/GraphCards/RegistrationsCard/useRegistrations/parse.ts',
  'app/components/admin/GraphCards/VisitorsCard/Chart/generateEmptyData.ts',
  'app/components/admin/GraphCards/VisitorsCard/useVisitors/parse.ts',
  'app/components/admin/GraphCards/_utils/query.ts',
  'app/components/admin/GraphCards/_utils/resolution.ts',
  'app/components/admin/GraphCards/_utils/timeSeries.test.ts',
  'app/components/admin/GraphCards/_utils/timeSeries.ts',
  'app/components/admin/GraphCards/typings.ts',
  'app/components/admin/UserBlockModals/BlockUser.tsx',
  'app/containers/Admin/Moderation/ModerationRow.tsx',
  'app/containers/Admin/dashboard/components/TimeControl.tsx',
  'app/containers/Admin/dashboard/overview/ChartFilters.tsx',
  'app/containers/Admin/dashboard/overview/charts/EmailDeliveriesCard/Chart/generateEmptyData.ts',
  'app/containers/Admin/dashboard/overview/charts/EmailDeliveriesCard/useEmailDeliveries/parse.test.ts',
  'app/containers/Admin/dashboard/overview/charts/EmailDeliveriesCard/useEmailDeliveries/parse.ts',
  'app/containers/Admin/dashboard/overview/charts/EventsCard/config.test.ts',
  'app/containers/Admin/dashboard/overview/charts/EventsCard/config.ts',
  'app/containers/Admin/dashboard/overview/charts/InvitationsCard/config.test.ts',
  'app/containers/Admin/dashboard/overview/charts/InvitationsCard/config.ts',
  'app/containers/Admin/dashboard/overview/charts/ProjectStatusCard/config.test.ts',
  'app/containers/Admin/dashboard/overview/charts/SelectableResourceByProjectChart.tsx',
  'app/containers/Admin/dashboard/overview/charts/SelectableResourceByTopicChart.tsx',
  'app/containers/Admin/dashboard/overview/getSensibleResolution.ts',
  'app/containers/Admin/dashboard/overview/index.tsx',
  'app/containers/Admin/dashboard/users/ChartFilters.tsx',
  'app/containers/Admin/dashboard/users/Charts/AgeChart/index.tsx',
  'app/containers/Admin/dashboard/users/Charts/AreaChart.tsx',
  'app/containers/Admin/dashboard/users/Charts/GenderChart/index.tsx',
  'app/containers/Admin/dashboard/users/index.tsx',
  'app/containers/Admin/dashboard/visitors/VisitorsOverview.tsx',
  'app/containers/Admin/dashboard/visitors/index.tsx',
  'app/containers/Admin/messaging/CustomEmails/Show/index.tsx',
  'app/containers/Admin/messaging/Edit/index.tsx',
  'app/containers/Admin/projects/project/analysis/TopBar/Filters/TimeFilter.tsx',
  'app/containers/Admin/projects/project/events/components/DateTimeSelection/index.tsx',
  'app/containers/Admin/projects/project/events/index.tsx',
  'app/containers/Admin/projects/project/inputImporter/ReviewSection/IdeaList.tsx',
  'app/containers/Admin/projects/project/insights/ParticipantsTimeline.tsx',
  'app/containers/Admin/projects/project/messaging/Show/index.tsx',
  'app/containers/Admin/projects/project/phase/PhaseHeader.tsx',
  'app/containers/Admin/projects/project/projectHeader/PublicationButtons/ScheduleLaunchModal/WhenSection.tsx',
  'app/containers/Admin/projects/project/projectHeader/PublicationButtons/ScheduleLaunchModal/index.tsx',
  'app/containers/Admin/projects/project/projectHeader/PublicationStatus.tsx',
  'app/containers/Admin/projects/project/traffic/TrafficDatesRange.tsx',
  'app/containers/Admin/reporting/components/ReportBuilder/Templates/ProjectTemplate/index.tsx',
  'app/containers/Admin/reporting/components/ReportBuilder/Templates/utils.ts',
  'app/containers/Admin/reporting/components/ReportBuilder/Toolbox/index.tsx',
  'app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/InternalAdoptionWidget/InternalAdoptionCard/index.tsx',
  'app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/InternalAdoptionWidget/useInternalAdoption/index.ts',
  'app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/ParticipantsWidget/ParticipantsCard/Narrow.tsx',
  'app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/ParticipantsWidget/ParticipantsCard/Wide.tsx',
  'app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/ParticipantsWidget/useParticipants/index.ts',
  'app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/ParticipationWidget/ParticipationCard/Narrow.tsx',
  'app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/ParticipationWidget/ParticipationCard/Wide.tsx',
  'app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/ParticipationWidget/ParticipationCard/generateEmptyData.ts',
  'app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/ParticipationWidget/useParticipation/index.ts',
  'app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/ParticipationWidget/useParticipation/parse/parseTimeSeries.test.ts',
  'app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/ParticipationWidget/useParticipation/parse/parseTimeSeries.ts',
  'app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/RegistrationsWidget/RegistrationsCard/Narrow.tsx',
  'app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/RegistrationsWidget/RegistrationsCard/Wide.tsx',
  'app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/RegistrationsWidget/useRegistrations/index.ts',
  'app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/VisitorsWidget/VisitorsCard/Narrow.tsx',
  'app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/VisitorsWidget/VisitorsCard/Wide.tsx',
  'app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/VisitorsWidget/useVisitors/index.ts',
  'app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/_deprecated/ReactionsByTimeWidget/ReactionsByTimeCard.tsx',
  'app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/_deprecated/ReactionsByTimeWidget/useReactionsByTime/index.tsx',
  'app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/_shared/A11yTable.tsx',
  'app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/utils.ts',
  'app/containers/Admin/reporting/components/ReportBuilder/Widgets/ProjectsWidget/ProjectsCard/ProjectRow.tsx',
  'app/containers/Admin/reporting/components/ReportBuilder/Widgets/ProjectsWidget/ProjectsCard/utils.test.ts',
  'app/containers/Admin/reporting/components/ReportBuilder/Widgets/ProjectsWidget/ProjectsCard/utils.ts',
  'app/containers/Admin/reporting/components/ReportBuilderPage/ReportRow/EditedText.tsx',
  'app/containers/Admin/users/_shared/UserManager/UsersTable/UsersTableRow/index.tsx',
  'app/containers/App/index.tsx',
  'app/containers/DisabledAccount/index.tsx',
  'app/containers/EventsPage/EventsViewer/index.tsx',
  'app/containers/IdeasShow/components/ProposalInfo/components/CountDown.tsx',
  'app/containers/UsersShowPage/UserHeader.tsx',
  'app/modules/commercial/admin_project_templates/admin/components/UseTemplateModal.tsx',
  'app/utils/__characterization__/dateFormats.test.ts',
  'app/utils/__characterization__/momentVsFacade.test.ts',
  'app/utils/__characterization__/schedulingPrimitives.test.ts',
  'app/utils/dataUtils/binAge.ts',
  'app/utils/dateUtils.test.ts',
  'app/utils/dateUtils.ts',
  // Compares moment against the façade on purpose; drop when the last
  // moment-using helper in dateUtils.ts is converted.
  'app/utils/__characterization__/dateFormats.test.ts',
  'app/utils/__characterization__/momentVsFacade.test.ts',
  'app/utils/__characterization__/schedulingPrimitives.test.ts',
  'app/utils/__characterization__/timezoneHelpers.test.ts',
  'app/utils/patchMomentDeAtJanuary.test.ts',
  'app/utils/patchMomentDeAtJanuary.ts',
];
