# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  install:
    docker:
      - image: joecridge1/node8-awscli-gitlfs-gulp
    working_directory: ~/cl2-front
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  lint_js:
    working_directory: ~/cl2-front
    steps:
      - run: npm run lint:js --silent

  lint_ts:
    working_directory: ~/cl2-front
    steps:
      - run: npm run lint:ts --silent

  deploy_demo:
    working_directory: ~/cl2-front
    steps:
      - run: npm run build
      - deploy:
        name: Deploy to S3 if tests pass and branch is Master
        command: aws s3 sync build/ s3://cl2-front-staging/ --delete --acl public-read

  deploy_crowdin:
    working_directory: ~/cl2-front
    steps:
      - run: CROWDIN_PLUGIN_ENABLED=true npm run build
      - deploy :
          name: Deploy translatable version to i18n.stg.citizenlab.co
          command: aws s3 sync build/ s3://cl2-front-translations/ --delete --acl public-read

workflows:
  version: 2
  build:
    jobs:
      - install
      - lint_js:
        requires:
          - install
      - lint_ts:
        required:
          - install
      - deploy_demo:
        required:
          - lint_js
          - lint_ts
        filters:
            branches:
              only:
                - master
      - deploy_crowdin:
        required:
          - lint_js
          - lint_ts
        filters:
            branches:
              only:
                - master
