# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:

  lint_js:
    docker:
      - image: citizenlabdotco/cl2-devops-front-buildenv
    working_directory: ~/cl2-front
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run lint:js --silent

  lint_ts:
    docker:
      - image: citizenlabdotco/cl2-devops-front-buildenv
    working_directory: ~/cl2-front
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run lint:ts --silent

  deploy_demo:
    docker:
      - image: citizenlabdotco/cl2-devops-front-buildenv
    working_directory: ~/cl2-front
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: SEGMENT_API_KEY=$SEGMENT_API_KEY_STAGING npm run build:staging
      - deploy:
          name: Deploy to S3 if tests pass and branch is Master
          command: aws s3 sync build/ s3://cl2-front-staging/ --delete --acl public-read

  deploy_crowdin:
    docker:
      - image: citizenlabdotco/cl2-devops-front-buildenv
    working_directory: ~/cl2-front
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: CROWDIN_PLUGIN_ENABLED=true SEGMENT_API_KEY=$SEGMENT_API_KEY_STAGING npm run build:staging
      - deploy :
          name: Deploy translatable version to i18n.stg.citizenlab.co
          command: aws s3 sync build/ s3://cl2-front-translations/ --delete --acl public-read

  deploy_production:
    docker:
      - image: citizenlabdotco/cl2-devops-front-buildenv
    working_directory: ~/cl2-front
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: SEGMENT_API_KEY=$SEGMENT_API_KEY_PRODUCTION npm run build
      - deploy :
          name: Deploy production version to benelux cluster
          command: aws s3 sync build/ s3://cl2-front-production-benelux/ --delete --acl public-read
      - deploy:
          name: Invalidate the static assets on the CDN
          command: aws cloudfront create-invalidation --distribution-id E2MY732QC516J3 --paths '/*'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - lint_js
      - lint_ts
      - deploy_demo:
          requires:
            - lint_js
            - lint_ts
          filters:
            branches:
              only: master
      - deploy_crowdin:
          requires:
            - lint_js
            - lint_ts
          filters:
            branches:
              only: master
      - deploy_production:
          requires:
            - lint_js
            - lint_ts
          filters:
            branches:
              only: production
