# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:

  lint_js:
    docker:
      - image: citizenlabdotco/cl2-devops-front-buildenv
    working_directory: ~/cl2-front
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run lint:js --silent

  lint_ts:
    docker:
      - image: citizenlabdotco/cl2-devops-front-buildenv
    working_directory: ~/cl2-front
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run lint:ts --silent

  extract_intl:
    docker:
      - image: citizenlabdotco/cl2-devops-front-buildenv
    working_directory: ~/cl2-front
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run extract-intl
      - run: git add app/translations/*.json
      - run: git config --global user.email "koen@citizenlab.co"
      - run: git config --global user.name "CircleCI"
      - add_ssh_keys
        fingerprints:
          - "54:03:ca:0f:4e:7a:fc:fa:6e:30:ef:80:2e:da:02:c4"
      - run: git diff --quiet && git diff --staged --quiet || git commit -m "[skip ci] Translations updated by CI (extract-intl)"
      - run: git push origin $CIRCLE_BRANCH

  build:
    docker:
      - image: citizenlabdotco/cl2-devops-front-buildenv
    working_directory: ~/cl2-front
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build

  deploy_demo:
    docker:
      - image: citizenlabdotco/cl2-devops-front-buildenv
    working_directory: ~/cl2-front
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: SEGMENT_API_KEY=$SEGMENT_API_KEY_STAGING npm run build:staging
      - deploy:
          name: Deploy to S3 if tests pass and branch is Master
          command: aws s3 sync build/ s3://cl2-front-staging/ --delete --acl public-read

  deploy_crowdin:
    docker:
      - image: citizenlabdotco/cl2-devops-front-buildenv
    working_directory: ~/cl2-front
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: CROWDIN_PLUGIN_ENABLED=true SEGMENT_API_KEY=$SEGMENT_API_KEY_STAGING npm run build:staging
      - deploy :
          name: Deploy translatable version to i18n.stg.citizenlab.co
          command: aws s3 sync build/ s3://cl2-front-translations/ --delete --acl public-read

  deploy_production:
    docker:
      - image: citizenlabdotco/cl2-devops-front-buildenv
    working_directory: ~/cl2-front
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: SEGMENT_API_KEY=$SEGMENT_API_KEY_PRODUCTION npm run build
      - deploy :
          name: Deploy production version to benelux cluster
          command: aws s3 sync build/ s3://cl2-front-production-benelux/ --delete --acl public-read
      - deploy:
          name: Invalidate the static assets on the CDN
          command: aws cloudfront create-invalidation --distribution-id E2MY732QC516J3 --paths '/*'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - lint_js:
          filters:
            branches:
              ignore: crowdin_master
      - lint_ts:
          filters:
            branches:
              ignore: crowdin_master
      - build:
          filters:
            branches:
              ignore: crowdin_master
      - extract_intl:
          filters:
            branches:
              ignore:
                - crowdin_master
                - master
      - deploy_demo:
          requires:
            - lint_js
            - lint_ts
            - build
          filters:
            branches:
              only: master
      - deploy_crowdin:
          requires:
            - lint_js
            - lint_ts
            - build
          filters:
            branches:
              only: master
      - deploy_production:
          requires:
            - lint_js
            - lint_ts
            - build
          filters:
            branches:
              only: production
