# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: joecridge1/node8-awscli-gitlfs-gulp

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/cl2-front

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      # - run: npm run test

      - run: npm run build

      - deploy:
          name: Deploy to S3 if tests pass and branch is Master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 sync build/ s3://cl2-front-staging/ --delete --acl public-read
            else
              echo "Not master branch so not deploying"
            fi

      - run: CROWDIN_PLUGIN_ENABLED=true npm run build

      - deploy :
          name: Deploy translatable version to i18n.stg.citizenlab.co
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 sync build/ s3://cl2-front-translations/ --delete --acl public-read
            else
              echo "Not master branch so not deploying"
            fi
