# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

executors:
  cl2-back:
    parameters:
      image-tag:
        type: string
    docker:
      - image: citizenlabdotco/cl2-back:<< parameters.image-tag >>
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: localhost
      - image: 'camptocamp/postgres:9.6'
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
jobs:

  build-docker-image:
    docker:
      - image: docker:stable-git
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run: |
          docker build -t citizenlabdotco/cl2-back:CIRCLE_SHA1 .
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push citizenlabdotco/cl2-back:CIRCLE_SHA1

  test:
    executor: 
      name: cl2-back
      image-tag: CIRCLE_SHA1
    working_directory: /cl2_back
    steps:
      - run: |
          rake db:create
          rake db:schema:load
      - run: |
          rspec

  # deploy_staging:
  #   machine: true
  #   steps:
  #     - run: |
  #         SSHU_VAR=SSH_STG_USER
  #         SSHH_VAR=SSH_STG_HOST
  #         ssh ${!SSHU_VAR}@${!SSHH_VAR} "docker pull citizenlabdotco/cl2-emails:latest && cd cl2-deployment && docker stack deploy --compose-file docker-compose-staging.yml cl2-back-stg --with-registry-auth"


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-docker-image:
          context: docker-hub-access
          filters:
            branches:
              ignore:
                - crowdin_master
      - test:
          context: docker-hub-access
          requires:
            - build-docker-image
          filters:
            branches:
              ignore:
                - crowdin_master

