import { getUpdatedConfiguration } from 'components/FormBuilder/utils';
import useFormCustomFields from 'hooks/useFormCustomFields';
import React, { lazy } from 'react';
import { useParams } from 'react-router-dom';
import { ideationConfig } from '../utils';

const FormBuilder = lazy(() => import('components/FormBuilder/edit'));

const IdeaFormBuilder = () => {
  const { projectId, phaseId } = useParams() as {
    projectId: string;
    phaseId?: string;
  };

  const formCustomFields = useFormCustomFields({
    projectId,
    phaseId,
  });

  const goBackUrl = `/admin/projects/${projectId}/ideaform`;

  const formCustomFields2 = [
    {
      id: 'c033360a-4e9d-4f17-ab78-39b0db8519a4',
      type: 'custom_field',
      key: 'ideation_section_1',
      input_type: 'section',
      title_multiloc: {
        en: 'What is your contribution?',
        'ar-MA': 'ما مساهمتك؟',
        'ar-SA': 'ما مساهمتك؟',
        'ca-ES': 'Quina és la vostra aportació?',
        'da-DK': 'Hvad er dit bidrag?',
        'de-DE': 'Was ist Ihr Beitrag?',
        'el-GR': 'Ποια είναι η συνεισφορά σας;',
        'en-CA': 'What is your contribution?',
        'en-GB': 'What is your contribution?',
        'es-CL': '¿Cuál es su contribución?',
        'es-ES': '¿Cuál es su contribución?',
        'fr-BE': 'Quelle est votre suggestion?',
        'fr-FR': 'Quelle est votre suggestion?',
        'hr-HR': 'Šta je vaš prilog ?',
        'hu-HU': 'What is your contribution ?',
        'it-IT': 'Qual è il suo contributo?',
        'kl-GL': 'Suna ilanngussaraajuk?',
        'lb-LU': 'Wat ass Äre Bäitrag ?',
        'lv-LV': 'Kāds ir jūsu ieguldījums?',
        mi: 'What is your contribution ?',
        'nb-NO': 'Hva er bidraget ditt?',
        'nl-BE': 'Wat is je bijdrage?',
        'nl-NL': 'Wat is je bijdrage?',
        'pl-PL': 'Jaki jest twój wkład ?',
        'pt-BR': 'Qual é a sua contribuição?',
        'ro-RO': 'Care este contribuția ta?',
        'sr-Latn': 'Šta je vaš prilog ?',
        'sr-SP': 'Шта је ваш прилог ?',
        'sv-SE': 'Vad är ditt bidrag?',
        'tr-TR': 'Katkınız nedir ?',
        ar: 'ما مساهمتك؟',
        ca: 'Quina és la vostra aportació?',
        da: 'Hvad er dit bidrag?',
        de: 'Was ist Ihr Beitrag?',
        el: 'Ποια είναι η συνεισφορά σας;',
        es: '¿Cuál es su contribución?',
        fr: 'Quelle est votre suggestion?',
        hr: 'Šta je vaš prilog ?',
        hu: 'What is your contribution ?',
        it: 'Qual è il suo contributo?',
        kl: 'Suna ilanngussaraajuk?',
        lb: 'Wat ass Äre Bäitrag ?',
        lv: 'Kāds ir jūsu ieguldījums?',
        nb: 'What is your contribution?',
        nl: 'Wat is je bijdrage?',
        pl: 'Jaki jest twój wkład ?',
        pt: 'Qual é a sua contribuição?',
        ro: 'Care este contribuția ta?',
        sr: 'What is your contribution?',
        sv: 'Vad är ditt bidrag?',
        tr: 'Katkınız nedir ?',
      },
      required: false,
      ordering: 0,
      enabled: true,
      code: 'ideation_section_1',
      created_at: null,
      updated_at: null,
      logic: {},
      description_multiloc: {},
      relationships: {
        options: {
          data: [],
        },
      },
    },
    {
      id: '08d141e2-bb77-40b6-8239-978e5d23c093',
      type: 'custom_field',
      key: 'title_multiloc',
      input_type: 'text_multiloc',
      title_multiloc: {
        en: 'Title',
        'ar-MA': 'العنوان',
        'ar-SA': 'العنوان',
        'ca-ES': 'Títol',
        'da-DK': 'Titel',
        'de-DE': 'Titel',
        'el-GR': 'Τίτλος',
        'en-CA': 'Title',
        'en-GB': 'Title',
        'es-CL': 'Título',
        'es-ES': 'Título',
        'fr-BE': 'Titre',
        'fr-FR': 'Titre',
        'hr-HR': 'Naslov',
        'hu-HU': 'Title',
        'it-IT': 'Titolo',
        'kl-GL': 'Atorfiup taaguutaa',
        'lb-LU': 'Titel',
        'lv-LV': 'Nosaukums',
        mi: 'Title',
        'nb-NO': 'Tittel',
        'nl-BE': 'Titel',
        'nl-NL': 'Titel',
        'pl-PL': 'Tytuł',
        'pt-BR': 'Assunto',
        'ro-RO': 'Titlu',
        'sr-Latn': 'Naslov',
        'sr-SP': 'Наслов',
        'sv-SE': 'Titel',
        'tr-TR': 'Başlık',
      },
      required: true,
      ordering: 1,
      enabled: true,
      code: 'title_multiloc',
      created_at: null,
      updated_at: null,
      logic: {},
      description_multiloc: {},
      relationships: {
        options: {
          data: [],
        },
      },
    },
    {
      id: '7f62fd71-9bda-4ef5-a1b6-388cab1523ba',
      type: 'custom_field',
      key: 'body_multiloc',
      input_type: 'html_multiloc',
      title_multiloc: {
        en: 'Description',
        'ar-MA': 'الوصف',
        'ar-SA': 'الوصف',
        'ca-ES': 'Descripció',
        'da-DK': 'Beskrivelse',
        'de-DE': 'Beschreibung',
        'el-GR': 'Περιγραφή',
        'en-CA': 'Description',
        'en-GB': 'Description',
        'es-CL': 'Descripción',
        'es-ES': 'Descripción',
        'fr-BE': 'Description complète',
        'fr-FR': 'Description',
        'hr-HR': 'Opis',
        'hu-HU': 'Description',
        'it-IT': 'Descrizione',
        'kl-GL': 'Nassuiaat',
        'lb-LU': 'Beschreiwung',
        'lv-LV': 'Apraksts',
        mi: 'Description',
        'nb-NO': 'Beskrivelse',
        'nl-BE': 'Beschrijving',
        'nl-NL': 'Beschrijving',
        'pl-PL': 'Opis',
        'pt-BR': 'Descrição',
        'ro-RO': 'Descriere',
        'sr-Latn': 'Opis',
        'sr-SP': 'Опис',
        'sv-SE': 'Beskrivning',
        'tr-TR': 'Açıklama',
      },
      required: true,
      ordering: 2,
      enabled: true,
      code: 'body_multiloc',
      created_at: null,
      updated_at: null,
      logic: {},
      description_multiloc: {},
      relationships: {
        options: {
          data: [],
        },
      },
    },
    {
      id: '992ad716-5a02-4439-b69f-0d0b2e6d105b',
      type: 'custom_field',
      key: null,
      input_type: 'section',
      title_multiloc: {
        en: 'Images and attachments',
        'ar-MA': 'Images and attachments',
        'ar-SA': 'Images and attachments',
        'ca-ES': 'Images and attachments',
        'da-DK': 'Images and attachments',
        'de-DE': 'Images and attachments',
        'el-GR': 'Images and attachments',
        'en-CA': 'Images and attachments',
        'en-GB': 'Images and attachments',
        'es-CL': 'Images and attachments',
        'es-ES': 'Images and attachments',
        'fr-BE': 'Images and attachments',
        'fr-FR': 'Images and attachments',
        'hr-HR': 'Images and attachments',
        'hu-HU': 'Images and attachments',
        'it-IT': 'Images and attachments',
        'kl-GL': 'Images and attachments',
        'lb-LU': 'Images and attachments',
        'lv-LV': 'Images and attachments',
        mi: 'Images and attachments',
        'nb-NO': 'Images and attachments',
        'nl-BE': 'Images and attachments',
        'nl-NL': 'Images and attachments',
        'pl-PL': 'Images and attachments',
        'pt-BR': 'Images and attachments',
        'ro-RO': 'Images and attachments',
        'sr-Latn': 'Images and attachments',
        'sr-SP': 'Images and attachments',
        'sv-SE': 'Images and attachments',
        'tr-TR': 'Images and attachments',
      },
      required: false,
      ordering: 3,
      enabled: true,
      code: null,
      created_at: null,
      updated_at: null,
      logic: {},
      description_multiloc: {},
      relationships: {
        options: {
          data: [],
        },
      },
    },
    {
      id: 'f9c31fac-f71d-463f-98a7-9b9d53942c9c',
      type: 'custom_field',
      key: 'idea_images_attributes',
      input_type: 'image_files',
      title_multiloc: {
        en: 'Images',
        'ar-MA': 'الصور',
        'ar-SA': 'الصور',
        'ca-ES': 'Images',
        'da-DK': 'Billeder',
        'de-DE': 'Bilder',
        'el-GR': 'Images',
        'en-CA': 'Images',
        'en-GB': 'Images',
        'es-CL': 'Imágenes',
        'es-ES': 'Imágenes',
        'fr-BE': 'Images',
        'fr-FR': 'Images',
        'hr-HR': 'Slike',
        'hu-HU': 'Images',
        'it-IT': 'Immagini',
        'kl-GL': 'Assit',
        'lb-LU': 'Biller',
        'lv-LV': 'Attēli',
        mi: 'Images',
        'nb-NO': 'Bilder',
        'nl-BE': 'Afbeeldingen',
        'nl-NL': 'Afbeeldingen',
        'pl-PL': 'Zdjęcia',
        'pt-BR': 'Imagens',
        'ro-RO': 'Imagini',
        'sr-Latn': 'Slike',
        'sr-SP': 'Слике',
        'sv-SE': 'Bilder',
        'tr-TR': 'Görseller',
      },
      required: false,
      ordering: 4,
      enabled: true,
      code: 'idea_images_attributes',
      created_at: null,
      updated_at: null,
      logic: {},
      description_multiloc: {},
      relationships: {
        options: {
          data: [],
        },
      },
    },
    {
      id: 'd4d795ce-af06-4dfc-a479-87003f5ab50b',
      type: 'custom_field',
      key: 'idea_files_attributes',
      input_type: 'files',
      title_multiloc: {
        en: 'Attachments',
        'ar-MA': 'المُرفقات',
        'ar-SA': 'المُرفقات',
        'ca-ES': 'Adjunts',
        'da-DK': 'Vedhæftede filer',
        'de-DE': 'Anhänge',
        'el-GR': 'Συνημμένα αρχεία',
        'en-CA': 'Other files',
        'en-GB': 'Other files',
        'es-CL': 'Archivos adjuntos',
        'es-ES': 'Archivos adjuntos',
        'fr-BE': 'Pièces jointes',
        'fr-FR': 'Pièces jointes',
        'hr-HR': 'Privici',
        'hu-HU': 'Other files',
        'it-IT': 'Allegati',
        'kl-GL': 'Filit ilanngussat',
        'lb-LU': 'Annexen',
        'lv-LV': 'Pielikumi',
        mi: 'Attachments',
        'nb-NO': 'Vedlegg',
        'nl-BE': 'Bijlagen',
        'nl-NL': 'Bijlagen',
        'pl-PL': 'Załączniki',
        'pt-BR': 'Anexos',
        'ro-RO': 'Fișiere atașate',
        'sr-Latn': 'Prilozi',
        'sr-SP': 'Прилози',
        'sv-SE': 'Bilagor',
        'tr-TR': 'Ekler',
      },
      required: false,
      ordering: 5,
      enabled: true,
      code: 'idea_files_attributes',
      created_at: null,
      updated_at: null,
      logic: {},
      description_multiloc: {},
      relationships: {
        options: {
          data: [],
        },
      },
    },
    {
      id: '49ec52dc-d852-4a51-af13-aa67b427b910',
      type: 'custom_field',
      key: null,
      input_type: 'section',
      title_multiloc: {
        en: 'Details',
        'ar-MA': 'Details',
        'ar-SA': 'Details',
        'ca-ES': 'Details',
        'da-DK': 'Details',
        'de-DE': 'Details',
        'el-GR': 'Details',
        'en-CA': 'Details',
        'en-GB': 'Details',
        'es-CL': 'Details',
        'es-ES': 'Details',
        'fr-BE': 'Details',
        'fr-FR': 'Details',
        'hr-HR': 'Details',
        'hu-HU': 'Details',
        'it-IT': 'Details',
        'kl-GL': 'Details',
        'lb-LU': 'Details',
        'lv-LV': 'Details',
        mi: 'Details',
        'nb-NO': 'Details',
        'nl-BE': 'Details',
        'nl-NL': 'Details',
        'pl-PL': 'Details',
        'pt-BR': 'Details',
        'ro-RO': 'Details',
        'sr-Latn': 'Details',
        'sr-SP': 'Details',
        'sv-SE': 'Details',
        'tr-TR': 'Details',
      },
      required: false,
      ordering: 6,
      enabled: true,
      code: null,
      created_at: null,
      updated_at: null,
      logic: {},
      description_multiloc: {},
      relationships: {
        options: {
          data: [],
        },
      },
    },
    {
      id: '379991fc-bfb0-4b7e-abc2-6a311d8fdae5',
      type: 'custom_field',
      key: 'location_description',
      input_type: 'text',
      title_multiloc: {
        en: 'Location',
        'ar-MA': 'الموقع',
        'ar-SA': 'الموقع',
        'ca-ES': 'Ubicació',
        'da-DK': 'Beliggenhed',
        'de-DE': 'Standort',
        'el-GR': 'Τοποθεσία',
        'en-CA': 'Location',
        'en-GB': 'Location',
        'es-CL': 'Ubicación',
        'es-ES': 'Ubicación',
        'fr-BE': 'Adresse',
        'fr-FR': 'Adresse',
        'hr-HR': 'Lokacija',
        'hu-HU': 'Location',
        'it-IT': 'Posizione',
        'kl-GL': 'Sumi',
        'lb-LU': 'Standuert',
        'lv-LV': 'Atrašanās vieta',
        mi: 'Location',
        'nb-NO': 'Lokalitet',
        'nl-BE': 'Locatie',
        'nl-NL': 'Locatie',
        'pl-PL': 'Lokalizacja',
        'pt-BR': 'Localização',
        'ro-RO': 'Locație',
        'sr-Latn': 'Lokacija',
        'sr-SP': 'Локација',
        'sv-SE': 'Plats',
        'tr-TR': 'Konum',
      },
      required: false,
      ordering: 8,
      enabled: true,
      code: 'location_description',
      created_at: null,
      updated_at: null,
      logic: {},
      description_multiloc: {},
      relationships: {
        options: {
          data: [],
        },
      },
    },
    {
      id: '124df894-002d-4df1-9e7c-0b61be36524f',
      type: 'custom_field',
      key: 'budget',
      input_type: 'number',
      title_multiloc: {
        en: 'Budget',
        'ar-MA': 'الميزانية',
        'ar-SA': 'الميزانية',
        'ca-ES': 'Pressupost',
        'da-DK': 'Budget',
        'de-DE': 'Budget',
        'el-GR': 'Προϋπολογισμός',
        'en-CA': 'Budget',
        'en-GB': 'Budget',
        'es-CL': 'Presupuesto',
        'es-ES': 'Presupuesto',
        'fr-BE': 'Budget',
        'fr-FR': 'Budget',
        'hr-HR': 'Proračun',
        'hu-HU': 'Budget',
        'it-IT': 'Bilancio',
        'kl-GL': 'Missingersuusiaq',
        'lb-LU': 'Budget',
        'lv-LV': 'Budžets',
        mi: 'Budget',
        'nb-NO': 'Budsjett',
        'nl-BE': 'Bedrag',
        'nl-NL': 'Bedrag',
        'pl-PL': 'Budżet',
        'pt-BR': 'Orçamento',
        'ro-RO': 'Buget',
        'sr-Latn': 'Budžet',
        'sr-SP': 'Буџет',
        'sv-SE': 'Budget',
        'tr-TR': 'Bütçe',
      },
      required: false,
      ordering: 9,
      enabled: true,
      code: 'budget',
      created_at: null,
      updated_at: null,
      logic: {},
      description_multiloc: {},
      relationships: {
        options: {
          data: [],
        },
      },
    },
    {
      id: 'c37c8fd2-5d49-4992-bad0-28e302304626',
      type: 'custom_field',
      key: 'proposed_budget',
      input_type: 'number',
      title_multiloc: {
        en: 'Proposed Budget',
        'ar-MA': 'الميزانية المُقترحة',
        'ar-SA': 'الميزانية المُقترحة',
        'ca-ES': 'Proposed Budget',
        'da-DK': 'Estimeret Budget',
        'de-DE': 'Vorgeschlagenes Budget',
        'el-GR': 'Proposed Budget',
        'en-CA': 'Proposed Budget',
        'en-GB': 'Proposed Budget',
        'es-CL': 'Proyecto de presupuesto',
        'es-ES': 'Proyecto de presupuesto',
        'fr-BE': 'Proposition de budget',
        'fr-FR': 'Proposition de budget',
        'hr-HR': 'Predloženi proračun',
        'hu-HU': 'Proposed Budget',
        'it-IT': 'Bilancio proposto',
        'kl-GL': 'Proposed Budget',
        'lb-LU': 'Proposéierte Budget',
        'lv-LV': 'Ierosinātais budžets',
        mi: 'Proposed Budget',
        'nb-NO': 'Proposed Budget',
        'nl-BE': 'Voorgesteld budget',
        'nl-NL': 'Voorgesteld budget',
        'pl-PL': 'Proponowany budżet',
        'pt-BR': 'Orçamento proposto',
        'ro-RO': 'Buget propus',
        'sr-Latn': 'Predloženi budžet',
        'sr-SP': 'Предложени буџет',
        'sv-SE': 'Budgetförslag',
        'tr-TR': 'Öngörülen Bütçe',
      },
      required: false,
      ordering: 10,
      enabled: false,
      code: 'proposed_budget',
      created_at: null,
      updated_at: null,
      logic: {},
      description_multiloc: {},
      relationships: {
        options: {
          data: [],
        },
      },
    },
    {
      id: 'd28c5e84-19c4-4a7d-b921-52450e4ce077',
      type: 'custom_field',
      key: 'author_id',
      input_type: 'text',
      title_multiloc: {
        en: 'Author',
        'ar-MA': 'المؤلف',
        'ar-SA': 'المؤلف',
        'ca-ES': 'Autor',
        'da-DK': 'Forfatter',
        'de-DE': 'Autor',
        'el-GR': 'Συντάκτης',
        'en-CA': 'Author',
        'en-GB': 'Author',
        'es-CL': 'Autor',
        'es-ES': 'Autor',
        'fr-BE': 'Auteur',
        'fr-FR': 'Auteur',
        'hr-HR': 'Autor',
        'hu-HU': 'Author',
        'it-IT': 'Autore',
        'kl-GL': 'Allattoq',
        'lb-LU': 'Auteur',
        'lv-LV': 'Autors',
        mi: 'Author',
        'nb-NO': 'Forfatter',
        'nl-BE': 'Auteur',
        'nl-NL': 'Auteur',
        'pl-PL': 'Autor',
        'pt-BR': 'Autor',
        'ro-RO': 'Autor',
        'sr-Latn': 'Autor',
        'sr-SP': 'Аутор',
        'sv-SE': 'Författare',
        'tr-TR': 'Yazan',
      },
      required: false,
      ordering: 11,
      enabled: true,
      code: 'author_id',
      created_at: null,
      updated_at: null,
      logic: {},
      description_multiloc: {},
      relationships: {
        options: {
          data: [],
        },
      },
    },
  ];

  console.log({ formCustomFields });

  return (
    <FormBuilder
      builderConfig={getUpdatedConfiguration(
        ideationConfig,
        formCustomFields2,
        goBackUrl
      )}
    />
  );
};

export default IdeaFormBuilder;
