import { getUpdatedConfiguration } from 'components/FormBuilder/utils';
import React, { lazy } from 'react';
import { useParams } from 'react-router-dom';
import { ideationConfig } from '../utils';

const FormBuilder = lazy(() => import('components/FormBuilder/edit'));

const IdeaFormBuilder = () => {
  const { projectId } = useParams() as {
    projectId: string;
  };

  // TODO: Remove hardcoded form custom field values when possible
  const formCustomFieldsDummy = [
    {
      id: 'a7a4ce2a-3284-47c2-be06-b2b38966caaf',
      type: 'custom_field',
      key: null,
      input_type: 'section',
      title_multiloc: {
        en: 'What is your idea ?',
        'ar-MA': 'ما فكرتك؟',
        'ar-SA': 'ما فكرتك؟',
        'ca-ES': 'Quina és la vostra idea ?',
        'da-DK': 'Hvad er din idé?',
        'de-DE': 'Was ist Ihre Idee?',
        'el-GR': 'What is your idea ?',
        'en-CA': 'What is your idea ?',
        'en-GB': 'What is your idea ?',
        'es-CL': '¿Cuál es su idea?',
        'es-ES': '¿Cuál es su idea?',
        'fr-BE': 'Quelle est votre idée ?',
        'fr-FR': 'Quelle est votre idée ?',
        'hr-HR': 'Što je vaša ideja?',
        'hu-HU': 'What is your idea ?',
        'it-IT': 'Qual è la sua idea?',
        'kl-GL': 'Suna isumassarsiaraajuk?',
        'lb-LU': 'Wat ass Är Iddi?',
        'lv-LV': 'Kāda ir jūsu ideja?',
        mi: 'What is your idea ?',
        'nb-NO': 'Hva er ideen din?',
        'nl-BE': 'Wat is je idee?',
        'nl-NL': 'Wat is je idee?',
        'pl-PL': 'Jaki jest Twój pomysł?',
        'pt-BR': 'Qual é a sua ideia?',
        'ro-RO': 'Care este ideea ta?',
        'sr-Latn': 'Šta je vaša ideja ?',
        'sr-SP': 'Шта је ваша идеја ?',
        'sv-SE': 'Vad är din idé?',
        'tr-TR': 'Fikriniz nedir ?',
        ar: 'ما فكرتك؟',
        ca: 'Quina és la vostra idea ?',
        da: 'Hvad er din idé?',
        de: 'Was ist Ihre Idee?',
        el: 'What is your idea ?',
        es: '¿Cuál es su idea?',
        fr: 'Quelle est votre idée ?',
        hr: 'Što je vaša ideja?',
        hu: 'What is your idea ?',
        it: 'Qual è la sua idea?',
        kl: 'Suna isumassarsiaraajuk?',
        lb: 'Wat ass Är Iddi?',
        lv: 'Kāda ir jūsu ideja?',
        nb: 'What is your idea ?',
        nl: 'Wat is je idee?',
        pl: 'Jaki jest Twój pomysł?',
        pt: 'Qual é a sua ideia?',
        ro: 'Care este ideea ta?',
        sr: 'What is your idea ?',
        sv: 'Vad är din idé?',
        tr: 'Fikriniz nedir ?',
      },
      required: false,
      ordering: 0,
      enabled: true,
      code: 'ideation_section_1',
      created_at: null,
      updated_at: null,
      logic: {},
      description_multiloc: {},
      constraints: {
        locks: {
          enabled: true,
          title_multiloc: true,
        },
      },
      relationships: {
        options: {
          data: [],
        },
      },
    },
    {
      id: '9e724098-a3da-4cd9-8eaa-32e4872faba0',
      type: 'custom_field',
      key: 'title_multiloc',
      input_type: 'text_multiloc',
      title_multiloc: {
        en: 'Title',
        'ar-MA': 'العنوان',
        'ar-SA': 'العنوان',
        'ca-ES': 'Títol',
        'da-DK': 'Titel',
        'de-DE': 'Titel',
        'el-GR': 'Τίτλος',
        'en-CA': 'Title',
        'en-GB': 'Title',
        'es-CL': 'Título',
        'es-ES': 'Título',
        'fr-BE': 'Titre',
        'fr-FR': 'Titre',
        'hr-HR': 'Naslov',
        'hu-HU': 'Title',
        'it-IT': 'Titolo',
        'kl-GL': 'Atorfiup taaguutaa',
        'lb-LU': 'Titel',
        'lv-LV': 'Nosaukums',
        mi: 'Title',
        'nb-NO': 'Tittel',
        'nl-BE': 'Titel',
        'nl-NL': 'Titel',
        'pl-PL': 'Tytuł',
        'pt-BR': 'Assunto',
        'ro-RO': 'Titlu',
        'sr-Latn': 'Naslov',
        'sr-SP': 'Наслов',
        'sv-SE': 'Titel',
        'tr-TR': 'Başlık',
      },
      required: true,
      ordering: 1,
      enabled: true,
      code: 'title_multiloc',
      created_at: null,
      updated_at: null,
      logic: {},
      description_multiloc: {},
      constraints: {
        locks: {
          enabled: true,
          required: true,
          title_multiloc: true,
        },
      },
      relationships: {
        options: {
          data: [],
        },
      },
    },
    {
      id: 'eab72888-e2ea-45c0-b784-40ff3a47164a',
      type: 'custom_field',
      key: 'body_multiloc',
      input_type: 'html_multiloc',
      title_multiloc: {
        en: 'Description',
        'ar-MA': 'الوصف',
        'ar-SA': 'الوصف',
        'ca-ES': 'Descripció',
        'da-DK': 'Beskrivelse',
        'de-DE': 'Beschreibung',
        'el-GR': 'Περιγραφή',
        'en-CA': 'Description',
        'en-GB': 'Description',
        'es-CL': 'Descripción',
        'es-ES': 'Descripción',
        'fr-BE': 'Description complète',
        'fr-FR': 'Description',
        'hr-HR': 'Opis',
        'hu-HU': 'Description',
        'it-IT': 'Descrizione',
        'kl-GL': 'Nassuiaat',
        'lb-LU': 'Beschreiwung',
        'lv-LV': 'Apraksts',
        mi: 'Description',
        'nb-NO': 'Beskrivelse',
        'nl-BE': 'Beschrijving',
        'nl-NL': 'Beschrijving',
        'pl-PL': 'Opis',
        'pt-BR': 'Descrição',
        'ro-RO': 'Descriere',
        'sr-Latn': 'Opis',
        'sr-SP': 'Опис',
        'sv-SE': 'Beskrivning',
        'tr-TR': 'Açıklama',
      },
      required: true,
      ordering: 2,
      enabled: true,
      code: 'body_multiloc',
      created_at: null,
      updated_at: null,
      logic: {},
      description_multiloc: {},
      constraints: {
        locks: {
          enabled: true,
          required: true,
          title_multiloc: true,
        },
      },
      relationships: {
        options: {
          data: [],
        },
      },
    },
    {
      id: 'aa64edb5-b9cc-4e39-b598-1c39277178a4',
      type: 'custom_field',
      key: null,
      input_type: 'section',
      title_multiloc: {
        en: 'Images and attachments',
        'ar-MA': 'Images and attachments',
        'ar-SA': 'Images and attachments',
        'ca-ES': 'Images and attachments',
        'da-DK': 'Images and attachments',
        'de-DE': 'Images and attachments',
        'el-GR': 'Images and attachments',
        'en-CA': 'Images and attachments',
        'en-GB': 'Images and attachments',
        'es-CL': 'Images and attachments',
        'es-ES': 'Images and attachments',
        'fr-BE': 'Images and attachments',
        'fr-FR': 'Images and attachments',
        'hr-HR': 'Images and attachments',
        'hu-HU': 'Images and attachments',
        'it-IT': 'Images and attachments',
        'kl-GL': 'Images and attachments',
        'lb-LU': 'Images and attachments',
        'lv-LV': 'Images and attachments',
        mi: 'Images and attachments',
        'nb-NO': 'Images and attachments',
        'nl-BE': 'Images and attachments',
        'nl-NL': 'Images and attachments',
        'pl-PL': 'Images and attachments',
        'pt-BR': 'Images and attachments',
        'ro-RO': 'Images and attachments',
        'sr-Latn': 'Images and attachments',
        'sr-SP': 'Images and attachments',
        'sv-SE': 'Images and attachments',
        'tr-TR': 'Images and attachments',
      },
      required: false,
      ordering: 3,
      enabled: true,
      code: 'ideation_section_2',
      created_at: null,
      updated_at: null,
      logic: {},
      description_multiloc: {},
      constraints: {},
      relationships: {
        options: {
          data: [],
        },
      },
    },
    {
      id: '08082dba-18c9-4740-822a-b12d781bbc7b',
      type: 'custom_field',
      key: 'idea_images_attributes',
      input_type: 'image_files',
      title_multiloc: {
        en: 'Images',
        'ar-MA': 'الصور',
        'ar-SA': 'الصور',
        'ca-ES': 'Images',
        'da-DK': 'Billeder',
        'de-DE': 'Bilder',
        'el-GR': 'Images',
        'en-CA': 'Images',
        'en-GB': 'Images',
        'es-CL': 'Imágenes',
        'es-ES': 'Imágenes',
        'fr-BE': 'Images',
        'fr-FR': 'Images',
        'hr-HR': 'Slike',
        'hu-HU': 'Images',
        'it-IT': 'Immagini',
        'kl-GL': 'Assit',
        'lb-LU': 'Biller',
        'lv-LV': 'Attēli',
        mi: 'Images',
        'nb-NO': 'Bilder',
        'nl-BE': 'Afbeeldingen',
        'nl-NL': 'Afbeeldingen',
        'pl-PL': 'Zdjęcia',
        'pt-BR': 'Imagens',
        'ro-RO': 'Imagini',
        'sr-Latn': 'Slike',
        'sr-SP': 'Слике',
        'sv-SE': 'Bilder',
        'tr-TR': 'Görseller',
      },
      required: false,
      ordering: 4,
      enabled: true,
      code: 'idea_images_attributes',
      created_at: null,
      updated_at: null,
      logic: {},
      description_multiloc: {},
      constraints: {
        locks: {
          enabled: true,
          title_multiloc: true,
        },
      },
      relationships: {
        options: {
          data: [],
        },
      },
    },
    {
      id: '9f67af9e-58b6-42f2-bbac-1b9b896caa49',
      type: 'custom_field',
      key: 'idea_files_attributes',
      input_type: 'files',
      title_multiloc: {
        en: 'Attachments',
        'ar-MA': 'المُرفقات',
        'ar-SA': 'المُرفقات',
        'ca-ES': 'Adjunts',
        'da-DK': 'Vedhæftede filer',
        'de-DE': 'Anhänge',
        'el-GR': 'Συνημμένα αρχεία',
        'en-CA': 'Other files',
        'en-GB': 'Other files',
        'es-CL': 'Archivos adjuntos',
        'es-ES': 'Archivos adjuntos',
        'fr-BE': 'Pièces jointes',
        'fr-FR': 'Pièces jointes',
        'hr-HR': 'Privici',
        'hu-HU': 'Other files',
        'it-IT': 'Allegati',
        'kl-GL': 'Filit ilanngussat',
        'lb-LU': 'Annexen',
        'lv-LV': 'Pielikumi',
        mi: 'Attachments',
        'nb-NO': 'Vedlegg',
        'nl-BE': 'Bijlagen',
        'nl-NL': 'Bijlagen',
        'pl-PL': 'Załączniki',
        'pt-BR': 'Anexos',
        'ro-RO': 'Fișiere atașate',
        'sr-Latn': 'Prilozi',
        'sr-SP': 'Прилози',
        'sv-SE': 'Bilagor',
        'tr-TR': 'Ekler',
      },
      required: false,
      ordering: 5,
      enabled: true,
      code: 'idea_files_attributes',
      created_at: null,
      updated_at: null,
      logic: {},
      description_multiloc: {},
      constraints: {
        locks: {
          title_multiloc: true,
        },
      },
      relationships: {
        options: {
          data: [],
        },
      },
    },
    {
      id: '3de39dad-db7c-4543-bd34-b51051d83b43',
      type: 'custom_field',
      key: null,
      input_type: 'section',
      title_multiloc: {
        en: 'Details',
        'ar-MA': 'Details',
        'ar-SA': 'Details',
        'ca-ES': 'Details',
        'da-DK': 'Details',
        'de-DE': 'Details',
        'el-GR': 'Details',
        'en-CA': 'Details',
        'en-GB': 'Details',
        'es-CL': 'Details',
        'es-ES': 'Details',
        'fr-BE': 'Details',
        'fr-FR': 'Details',
        'hr-HR': 'Details',
        'hu-HU': 'Details',
        'it-IT': 'Details',
        'kl-GL': 'Details',
        'lb-LU': 'Details',
        'lv-LV': 'Details',
        mi: 'Details',
        'nb-NO': 'Details',
        'nl-BE': 'Details',
        'nl-NL': 'Details',
        'pl-PL': 'Details',
        'pt-BR': 'Details',
        'ro-RO': 'Details',
        'sr-Latn': 'Details',
        'sr-SP': 'Details',
        'sv-SE': 'Details',
        'tr-TR': 'Details',
      },
      required: false,
      ordering: 6,
      enabled: true,
      code: 'ideation_section_3',
      created_at: null,
      updated_at: null,
      logic: {},
      description_multiloc: {},
      constraints: {},
      relationships: {
        options: {
          data: [],
        },
      },
    },
    {
      id: 'dde57c09-a793-497e-bf6f-5d31bb56d18d',
      type: 'custom_field',
      key: 'location_description',
      input_type: 'text',
      title_multiloc: {
        en: 'Location',
        'ar-MA': 'الموقع',
        'ar-SA': 'الموقع',
        'ca-ES': 'Ubicació',
        'da-DK': 'Beliggenhed',
        'de-DE': 'Standort',
        'el-GR': 'Τοποθεσία',
        'en-CA': 'Location',
        'en-GB': 'Location',
        'es-CL': 'Ubicación',
        'es-ES': 'Ubicación',
        'fr-BE': 'Adresse',
        'fr-FR': 'Adresse',
        'hr-HR': 'Lokacija',
        'hu-HU': 'Location',
        'it-IT': 'Posizione',
        'kl-GL': 'Sumi',
        'lb-LU': 'Standuert',
        'lv-LV': 'Atrašanās vieta',
        mi: 'Location',
        'nb-NO': 'Lokalitet',
        'nl-BE': 'Locatie',
        'nl-NL': 'Locatie',
        'pl-PL': 'Lokalizacja',
        'pt-BR': 'Localização',
        'ro-RO': 'Locație',
        'sr-Latn': 'Lokacija',
        'sr-SP': 'Локација',
        'sv-SE': 'Plats',
        'tr-TR': 'Konum',
      },
      required: false,
      ordering: 8,
      enabled: true,
      code: 'location_description',
      created_at: null,
      updated_at: null,
      logic: {},
      description_multiloc: {},
      constraints: {
        locks: {
          title_multiloc: true,
        },
      },
      relationships: {
        options: {
          data: [],
        },
      },
    },
    {
      id: '343b987f-f0c3-4ed3-a945-c26ff4c52327',
      type: 'custom_field',
      key: 'budget',
      input_type: 'number',
      title_multiloc: {
        en: 'Budget',
        'ar-MA': 'الميزانية',
        'ar-SA': 'الميزانية',
        'ca-ES': 'Pressupost',
        'da-DK': 'Budget',
        'de-DE': 'Budget',
        'el-GR': 'Προϋπολογισμός',
        'en-CA': 'Budget',
        'en-GB': 'Budget',
        'es-CL': 'Presupuesto',
        'es-ES': 'Presupuesto',
        'fr-BE': 'Budget',
        'fr-FR': 'Budget',
        'hr-HR': 'Proračun',
        'hu-HU': 'Budget',
        'it-IT': 'Bilancio',
        'kl-GL': 'Missingersuusiaq',
        'lb-LU': 'Budget',
        'lv-LV': 'Budžets',
        mi: 'Budget',
        'nb-NO': 'Budsjett',
        'nl-BE': 'Bedrag',
        'nl-NL': 'Bedrag',
        'pl-PL': 'Budżet',
        'pt-BR': 'Orçamento',
        'ro-RO': 'Buget',
        'sr-Latn': 'Budžet',
        'sr-SP': 'Буџет',
        'sv-SE': 'Budget',
        'tr-TR': 'Bütçe',
      },
      required: false,
      ordering: 9,
      enabled: true,
      code: 'budget',
      created_at: null,
      updated_at: null,
      logic: {},
      description_multiloc: {},
      constraints: {},
      relationships: {
        options: {
          data: [],
        },
      },
    },
    {
      id: '30157674-5e92-4e2c-af14-2c18dd656a4a',
      type: 'custom_field',
      key: 'proposed_budget',
      input_type: 'number',
      title_multiloc: {
        en: 'Proposed Budget',
        'ar-MA': 'الميزانية المُقترحة',
        'ar-SA': 'الميزانية المُقترحة',
        'ca-ES': 'Proposed Budget',
        'da-DK': 'Estimeret Budget',
        'de-DE': 'Vorgeschlagenes Budget',
        'el-GR': 'Proposed Budget',
        'en-CA': 'Proposed Budget',
        'en-GB': 'Proposed Budget',
        'es-CL': 'Proyecto de presupuesto',
        'es-ES': 'Proyecto de presupuesto',
        'fr-BE': 'Proposition de budget',
        'fr-FR': 'Proposition de budget',
        'hr-HR': 'Predloženi proračun',
        'hu-HU': 'Proposed Budget',
        'it-IT': 'Bilancio proposto',
        'kl-GL': 'Proposed Budget',
        'lb-LU': 'Proposéierte Budget',
        'lv-LV': 'Ierosinātais budžets',
        mi: 'Proposed Budget',
        'nb-NO': 'Proposed Budget',
        'nl-BE': 'Voorgesteld budget',
        'nl-NL': 'Voorgesteld budget',
        'pl-PL': 'Proponowany budżet',
        'pt-BR': 'Orçamento proposto',
        'ro-RO': 'Buget propus',
        'sr-Latn': 'Predloženi budžet',
        'sr-SP': 'Предложени буџет',
        'sv-SE': 'Budgetförslag',
        'tr-TR': 'Öngörülen Bütçe',
      },
      required: false,
      ordering: 10,
      enabled: false,
      code: 'proposed_budget',
      created_at: null,
      updated_at: null,
      logic: {},
      description_multiloc: {},
      constraints: {},
      relationships: {
        options: {
          data: [],
        },
      },
    },
    {
      id: 'ae47180b-9eba-49da-8151-42b1b78492f9',
      type: 'custom_field',
      key: 'author_id',
      input_type: 'text',
      title_multiloc: {
        en: 'Author',
        'ar-MA': 'المؤلف',
        'ar-SA': 'المؤلف',
        'ca-ES': 'Autor',
        'da-DK': 'Forfatter',
        'de-DE': 'Autor',
        'el-GR': 'Συντάκτης',
        'en-CA': 'Author',
        'en-GB': 'Author',
        'es-CL': 'Autor',
        'es-ES': 'Autor',
        'fr-BE': 'Auteur',
        'fr-FR': 'Auteur',
        'hr-HR': 'Autor',
        'hu-HU': 'Author',
        'it-IT': 'Autore',
        'kl-GL': 'Allattoq',
        'lb-LU': 'Auteur',
        'lv-LV': 'Autors',
        mi: 'Author',
        'nb-NO': 'Forfatter',
        'nl-BE': 'Auteur',
        'nl-NL': 'Auteur',
        'pl-PL': 'Autor',
        'pt-BR': 'Autor',
        'ro-RO': 'Autor',
        'sr-Latn': 'Autor',
        'sr-SP': 'Аутор',
        'sv-SE': 'Författare',
        'tr-TR': 'Yazan',
      },
      required: false,
      ordering: 11,
      enabled: true,
      code: 'author_id',
      created_at: null,
      updated_at: null,
      logic: {},
      description_multiloc: {},
      constraints: {},
      relationships: {
        options: {
          data: [],
        },
      },
    },
  ];

  const goBackUrl = `/admin/projects/${projectId}/ideaform`;

  return (
    <FormBuilder
      builderConfig={getUpdatedConfiguration(
        ideationConfig,
        formCustomFieldsDummy,
        goBackUrl
      )}
    />
  );
};

export default IdeaFormBuilder;
