export default {
  analysisForSurveyDeleted: 'Analysis for survey deleted',
  analysisCreated: 'Analysis created',
  manualTagCreated: 'Manual tag created',
  automatedTagCreated: 'Automated tag created',
  tagDeleted: 'Tag deleted',
  tagAssignmentCreated: 'Tag assignment created',
  tagAssignmentDeleted: 'Tag assignment deleted',
  summaryCreated: 'Auto summary created',
  summaryDeleted: 'Auto summary deleted',
  questionCreated: 'Question created',
  questionDeleted: 'Question deleted',
  bulkTagAssignmentPerformed: 'Bulk tag assignment performed',
  autoTaggingPerformed: 'Auto tagging with predefined tags performed',
  tagFilterUsed: 'Tag filter used',
  authorFilterUsed: 'Author filter used',
  engagementFilterUsed: 'Engagement filter used',
  timeFilterUsed: 'Time filter used',
  inputCustomFieldFilterUsed: 'Input custom field filter used',
  inputPreviewedFromList: 'Input previewed',
  inputPreviewedFromQuestion: 'Input previewed from question',
  inputPreviewedFromSummary: 'Input previewed from summary',
  addQuestionToAIAnalysis: 'Add question to AI analysis',
  removeQuestionFromAIAnalysis: 'Remove question from AI analysis',
  regenerateAIInsights: 'Regenerate AI insights',
  openReportBuilderAITab: 'Open report builder AI tab',
  dragAndDropInsightInReportBuilder: 'Drag and drop insight in report builder',
};
