import {
  viewportWidths,
  media,
  colors,
  fontSizes,
  defaultStyles,
  defaultCardStyle,
  defaultCardHoverStyle,
  defaultOutline,
  defaultInputStyle,
  stylingConsts,
  quillEditedContent,
  getTheme,
  invisibleA11yText,
  remCalc,
  calculateContrastRatio,
  hexToRgb,
  isRtl,
} from '@citizenlab/cl2-component-library';

const defaultAdminCardPadding = 40;

export {
  viewportWidths,
  media,
  colors,
  fontSizes,
  defaultStyles,
  defaultCardStyle,
  defaultCardHoverStyle,
  defaultOutline,
  defaultInputStyle,
  stylingConsts,
  quillEditedContent,
  getTheme,
  invisibleA11yText,
  remCalc,
  calculateContrastRatio,
  hexToRgb,
  isRtl,
  defaultAdminCardPadding,
};
