require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  AutoCorrect: false
  Exclude:
  - 'db/schema.rb'
  - '**/*.builder'
  - '**/.*.*'
  - '**/bin/**/*'

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'shared_examples', 'class_eval']
  Enabled: true
  Exclude:
  - '**/spec/**/*'
  - 'db/migrate/**/*'
  # Max: 25
Metrics/MethodLength:
  Enabled: true
  Max: 50
  IgnoredMethods: ['included', 'prepended', 'extended']
  Exclude:
  - 'db/migrate/**/*'
Metrics/AbcSize:
  Enabled: false
  IgnoredMethods: ['included', 'prepended', 'extended']
  # Max: 10
  Exclude:
  - 'db/migrate/**/*'
Metrics/ClassLength:
  Enabled: true
  # Max: 100
Layout/LineLength:
  Enabled: true
  # Max: 120
Rails/LexicallyScopedActionFilter:
  Enabled: true
Style/Documentation:
  Enabled: true
  Exclude:
  - 'db/migrate/**/*'
Style/FrozenStringLiteralComment:
  Enabled: false
  AutoCorrect: true
Style/SymbolArray:
  AutoCorrect: true
Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
RSpec/DescribeClass:
  Exclude:
  - '**/spec/acceptance/**/*'
  - '**/spec/lint/**/*'
Rspec/SharedContext:
  Exclude:
  - '**/spec/acceptance/**/*'
Rspec/MultipleMemoizedHelpers:
  Exclude:
  - '**/spec/acceptance/**/*'
Rspec/EmptyExampleGroup:
  Exclude:
  - '**/spec/acceptance/**/*'
RSpec/MultipleExpectations:
  Max: 2
  Exclude:
    - '**/spec/acceptance/**/*'
RSpec/ExampleLength:
  Max: 10
RSpec/MessageSpies:
  Enabled: false
