inherit_from:
  - .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
  - 'db/schema.rb'
  - '**/*.builder'
  - '**/.*.*'
  - '**/bin/**/*'
  - 'engines/ee/**/*'

Style/Documentation:
  # Most classes are not documented, so turn off this Cop.
  Enabled: false

Style/SymbolProc:
  Enabled: true
  IgnoredMethods:
    - attribute
    - throttle
  Exclude:
    - 'db/migrate/**/*'

Style/NumericPredicate:
  # Turned off because `something == 0` and `something.zero?`
  # are not the same if `something` is not a number.
  Enabled: false

Layout/FirstHashElementIndentation:
  # Wait for a decision on Layout/HashAlignment.
  Enabled: false
  EnforcedStyle: consistent

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/TrailingWhitespace:
  AllowInHeredoc: true

Metrics/ClassLength:
  Max: 300
  CountAsOne: ['array', 'hash', 'heredoc']

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

RSpec/MultipleExpectations:
  # It makes little sense to disallow multiple expectations in one example,
  # so turn off this Cop.
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Rails/DynamicFindBy:
  AllowedMethods:
    - find_by_cimail
    - find_by_cimail!
    - find_by_card_id

RSpec/SharedContext:
  Exclude:
  - '**/spec/acceptance/**/*'

Gemspec/RequireMFA:
# Discussion needed
  Enabled: false

Style/FetchEnvVar:
# Discussion needed
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Rails/I18nLocaleTexts:
# Discussion needed
  Enabled: false

Layout/MultilineMethodCallIndentation:
  # We need a discussion on this because we have 347 offences against the default
  # and 252 offences against "EnforcedStyle: indented".
  EnforcedStyle: indented

RSpec/DescribeClass:
  IgnoredMetadata:
    type: ['request']

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  IgnoredMethods: ['included', 'prepended', 'extended']
  Exclude:
  - 'db/migrate/**/*'
