# This file collects all Cops that we like to have, but for some reason
# not all offences can be fixed. The exceptions are in .rubocop_todo.yml.
# When all offences of a Cop are fixed, then the Cop can be moved to
# .rubocop.yml.

Metrics/MethodLength:
  Enabled: true
  Max: 30
  CountAsOne: ['array', 'hash', 'heredoc']
  IgnoredMethods: ['included', 'prepended', 'extended']
  Exclude:
  - 'db/migrate/**/*'
