# This file collects all Cops that we like to have, but for some reason
# not all offences can be fixed. The exceptions are in .rubocop_todo.yml.
# When all offences of a Cop are fixed, then the Cop can be moved to
# .rubocop.yml and the Cop has to be removed from .rubocop_todo.yml.

Metrics/MethodLength:
  Enabled: true
  Max: 30
  CountAsOne: ['array', 'hash', 'heredoc']
  IgnoredMethods: ['included', 'prepended', 'extended']
  Exclude:
  - 'db/migrate/**/*'

Metrics/BlockLength:
  Enabled: true

Metrics/AbcSize:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: true

Style/MutableConstant:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: true

Style/GuardClause:
  Enabled: true

Layout/LineLength:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  Enabled: true
  # We need a discussion on this because we have 347 offences against the default
  # and 252 offences against "EnforcedStyle: indented".
  EnforcedStyle: indented

Lint/UselessAssignment:
  Enabled: true

RSpec/ExampleLength:
  Enabled: true

RSpec/InstanceVariable:
  Enabled: true

RSpec/DescribedClass:
  Enabled: true

RSpec/EmptyExampleGroup:
  Enabled: true

RSpec/ContextWording:
  Enabled: true

RSpec/MultipleMemoizedHelpers:
  Enabled: true

RSpec/MissingExampleGroupArgument:
  Enabled: true

RSpec/LetSetup:
  Enabled: true

RSpec/MessageSpies:
  Enabled: true

RSpec/FilePath:
  Enabled: true

RSpec/ExampleWording:
  Enabled: true

RSpec/PredicateMatcher:
  Enabled: true

RSpec/ScatteredSetup:
  Enabled: true

RSpec/EmptyLineAfterFinalLet:
  Enabled: true

RSpec/NamedSubject:
  Enabled: true

RSpec/AnyInstance:
  Enabled: true

RSpec/NestedGroups:
  Enabled: true

RSpec/RepeatedDescription:
  Enabled: true

RSpec/DescribeClass:
  Enabled: true
  IgnoredMetadata:
    type: ['request']

Rails/TimeZone:
  Enabled: true
