inherit_from:
  - .rubocop_desired.yml
  - .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  DisabledByDefault: true
  Exclude:
  - 'db/schema.rb'
  - '**/*.builder'
  - '**/.*.*'
  - '**/bin/**/*'
  - 'engines/ee/**/*'

Style/StringLiterals:
  Enabled: true

Style/HashSyntax:
  Enabled: true

Style/Semicolon:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  Enabled: true

Style/Documentation:
  # Most classes are not documented, so turn off this Cop.
  Enabled: false

Style/WordArray:
  Enabled: true

Style/BlockDelimiters:
  Enabled: true

Style/PercentLiteralDelimiters:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/NegatedIf:
  Enabled: true

Style/StringLiteralsInInterpolation:
  Enabled: true

Style/Proc:
  Enabled: true

Style/SymbolProc:
  Enabled: true
  IgnoredMethods:
    - attribute
    - throttle
  Exclude:
    - 'db/migrate/**/*'

Style/TrailingCommaInArrayLiteral:
  Enabled: true

Style/SpecialGlobalVars:
  Enabled: true

Style/EmptyMethod:
  Enabled: true

Style/ExpandPathArguments:
  Enabled: true

Style/NestedParenthesizedCalls:
  Enabled: true

Style/CommentAnnotation:
  Enabled: true

Style/TrailingCommaInArguments:
  Enabled: true

Style/NumericLiterals:
  Enabled: true

Style/ClassCheck:
  Enabled: true

Style/Lambda:
  Enabled: true

Style/AndOr:
  Enabled: true

Style/EmptyElse:
  Enabled: true

Style/OneLineConditional:
  Enabled: true

Style/StringConcatenation:
  Enabled: true

Style/RegexpLiteral:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/Next:
  Enabled: true

Style/NumericPredicate:
  # Turned off because `something == 0` and `something.zero?`
  # are not the same if `something` is not a number.
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true
  AllowInHeredoc: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/HashAlignment:
  # There are a lot of places where EnforcedColonStyle: table is expected.
  # Discussion needed, because the default will affect a lot of table like hash literals.
  Enabled: false

Layout/FirstHashElementIndentation:
  # Wait for a decision on Layout/HashAlignment.
  Enabled: false
  EnforcedStyle: consistent

Layout/EmptyLines:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Layout/IndentationConsistency:
  Enabled: true

Layout/MultilineBlockLayout:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: true

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/SpaceAfterColon:
  Enabled: true

Layout/CaseIndentation:
  Enabled: true
  EnforcedStyle: end

Layout/LeadingEmptyLines:
  Enabled: true

Layout/AssignmentIndentation:
  Enabled: true

Layout/SpaceAroundBlockParameters:
  Enabled: true

Layout/SpaceBeforeComment:
  Enabled: true

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: true

Layout/ClosingParenthesisIndentation:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/DotPosition:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Layout/SpaceInLambdaLiteral:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Naming/VariableNumber:
  Enabled: true

Metrics/ClassLength:
  Enabled: true
  Max: 300
  CountAsOne: ['array', 'hash', 'heredoc']

Lint/UnusedMethodArgument:
  Enabled: true
  AllowUnusedKeywordArguments: true

Lint/ParenthesesAsGroupedExpression:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true

RSpec/MultipleExpectations:
  # It makes little sense to disallow multiple expectations in one example,
  # so turn off this Cop.
  Enabled: false

RSpec/ImplicitExpect:
  Enabled: true

RSpec/EmptyLineAfterHook:
  Enabled: true

RSpec/ScatteredLet:
  Enabled: true

RSpec/EmptyLineAfterFinalLet:
  Enabled: true

RSpec/EmptyLineAfterExample:
  Enabled: true

RSpec/NotToNot:
  Enabled: true

RSpec/EmptyLineAfterSubject:
  Enabled: true

RSpec/EmptyLineAfterExampleGroup:
  Enabled: true

Rails/HttpStatus:
  Enabled: true

Rails/PluralizationGrammar:
  Enabled: true

Rails/IndexWith:
  Enabled: true

Performance/Detect:
  Enabled: true

Performance/TimesMap:
  Enabled: true

# This was the original file contents. We will enable Cops one by one.
# 
# Metrics/BlockLength:
#   IgnoredMethods: ['describe', 'context', 'shared_examples', 'class_eval']
#   Enabled: true
#   Exclude:
#   - '**/spec/**/*'
#   - 'db/migrate/**/*'
#   # Max: 25
# Metrics/MethodLength:
#   Enabled: true
#   Max: 30
#   IgnoredMethods: ['included', 'prepended', 'extended']
#   Exclude:
#   - 'db/migrate/**/*'
# Metrics/AbcSize:
#   Enabled: true
#   IgnoredMethods: ['included', 'prepended', 'extended']
#   Exclude:
#   - 'db/migrate/**/*'
# Metrics/ClassLength:
#   Enabled: true
#   # Max: 100
# Layout/HashAlignment:
#   EnforcedColonStyle: [key, table]
#   EnforcedHashRocketStyle: [key, table]
# Layout/LineLength:
#   Enabled: true
#   # Max: 120
# Rails/LexicallyScopedActionFilter:
#   Enabled: true
# Style/Documentation:
#   Enabled: true
#   Exclude:
#   - 'db/migrate/**/*'
# Style/EmptyElse:
#   Enabled: false
# Style/FrozenStringLiteralComment:
#   Enabled: false
#   AutoCorrect: true
# Style/GuardClause:
#   Enabled: false
# Style/MultilineBlockChain:
#   Enabled: false
# Style/NegatedIf:
#   Enabled: false
# Style/NumericPredicate:
#   # Zero is sometimes considered to be both 
#   # positive as well as negative, which is why I
#   # strongly disagree (this can only lead to more
#   # confusion).
#   Enabled: false
# Style/SymbolArray:
#   AutoCorrect: true
# Documentation:
#   Enabled: false
# Style/ClassAndModuleChildren:
#   Enabled: false
# RSpec/ContextWording:
#   Exclude:
#     - '**/spec/policies/**/*'
# RSpec/DescribeClass:
#   Exclude:
#   - '**/spec/acceptance/**/*'
#   - '**/spec/lint/**/*'
# RSpec/SharedContext:
#   Exclude:
#   - '**/spec/acceptance/**/*'
# RSpec/MultipleMemoizedHelpers:
#   Exclude:
#   - '**/spec/acceptance/**/*'
# RSpec/EmptyExampleGroup:
#   Exclude:
#   - '**/spec/acceptance/**/*'
# RSpec/MultipleExpectations:
#   Enabled: false
# RSpec/ExampleLength:
#   Max: 20
# RSpec/MessageSpies:
#   Enabled: false
Style/AccessorGrouping:
  Enabled: true
Style/BlockComments:
  Enabled: true
Style/CaseEquality:
  Enabled: true
Style/CaseLikeIf:
  Enabled: true
Style/ClassEqualityComparison:
  Enabled: true
Style/ColonMethodCall:
  Enabled: true
Style/CommentedKeyword:
  Enabled: true
Style/ConditionalAssignment:
  Enabled: true
Style/DefWithParentheses:
  Enabled: true
Style/DoubleNegation:
  Enabled: false
Style/EachWithObject:
  Enabled: true
Style/EmptyLiteral:
  Enabled: true
Style/EvenOdd:
  Enabled: true
Style/ExplicitBlockArgument:
  Enabled: true
Style/GlobalStdStream:
  Enabled: true
Style/HashAsLastArrayItem:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/IdenticalConditionalBranches:
  Enabled: true
Style/IfInsideElse:
  Enabled: true
Style/InfiniteLoop:
  Enabled: true
Style/InverseMethods:
  Enabled: true
Style/KeywordParametersOrder:
  Enabled: true
Style/MethodCallWithoutArgsParentheses:
  Enabled: true
Style/MultilineIfModifier:
  Enabled: true
Style/MultilineTernaryOperator:
  Enabled: true
Style/MultilineWhenThen:
  Enabled: true
Style/MultipleComparison:
  Enabled: true
Style/NilComparison:
  Enabled: true
Style/NonNilCheck:
  Enabled: true
Style/Not:
  Enabled: true
Style/ParallelAssignment:
  Enabled: true
Style/ParenthesesAroundCondition:
  Enabled: true
Style/PreferredHashMethods:
  Enabled: true
Style/RaiseArgs:
  Enabled: true
Style/RandomWithOffset:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true
Style/RedundantCondition:
  Enabled: true
Style/RedundantException:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantInterpolation:
  Enabled: true
Style/RedundantPercentQ:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantReturn:
  Enabled: true
Style/RedundantSort:
  Enabled: true
Style/RescueModifier:
  Enabled: true
Style/RescueStandardError:
  Enabled: true
Style/SafeNavigation:
  Enabled: true
Style/Sample:
  Enabled: true
Style/SignalException:
  Enabled: true
Style/SingleLineMethods:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
Style/SoleNestedConditional:
  Enabled: true
Style/SymbolLiteral:
  Enabled: true
Style/TernaryParentheses:
  Enabled: true
Style/TrivialAccessors:
  Enabled: true
Style/ZeroLengthPredicate:
  Enabled: true

Performance/FlatMap:
  Enabled: true
Performance/Count:
  Enabled: true
Performance/InefficientHashSearch:
  Enabled: true
Performance/RedundantBlockCall:
  Enabled: true
Performance/RedundantMerge:
  Enabled: true
Performance/RegexpMatch:
  Enabled: true
Performance/ReverseEach:
  Enabled: true
Performance/StringReplacement:
  Enabled: true
