inherit_from:
  - .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - ./lib/rubocop/cop/forbidden_app_configuration_method.rb

AllCops:
  DisplayStyleGuide: true
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "**/*.builder"
    - "**/.*.*"
    - "**/bin/**/*"
    - "engines/ee/**/*"
    - "vendor/**/*"
    - "**/create_tenant.rake"

Layout/HashAlignment:
  EnforcedColonStyle: [key, table]
  EnforcedHashRocketStyle: [key, table]

Metrics/BlockLength:
  Max: 384
  Exclude:
    - "engines/*/*/spec/**/*"
    - "spec/**/*"

Style/Documentation:
  # Most classes are not documented, so turn off this Cop.
  Enabled: false

Style/GuardClause:
  Enabled: false
Style/Next:
  Enabled: false

Style/SymbolProc:
  Enabled: true
  AllowedMethods:
    - attribute
    - throttle
  Exclude:
    - "db/migrate/**/*"

Style/FormatStringToken:
  Enabled: false

Style/NumericPredicate:
  # Turned off because `something == 0` and `something.zero?`
  # are not the same if `something` is not a number.
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/TrailingWhitespace:
  AllowInHeredoc: true

Lint/AmbiguousBlockAssociation:
  AllowedPatterns:
    - change

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

RSpec/MultipleExpectations:
  # It makes little sense to disallow multiple expectations in one example,
  # so turn off this Cop.
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Rails/DynamicFindBy:
  AllowedMethods:
    - find_by_cimail
    - find_by_cimail!
    - find_by_card_id

Rails/CreateTableWithTimestamps:
  # Some migrations do not add timestamps, so they are excluded.
  Exclude:
    - "db/migrate/20170318143940_create_join_table_projects_topics.rb"
    - "db/migrate/20170318144700_create_join_table_areas_projects.rb"
    - "db/migrate/20170318181018_create_join_table_ideas_topics.rb"
    - "db/migrate/20170319000059_create_join_table_areas_ideas.rb"
    - "db/migrate/20171010114629_create_groups_projects.rb"
    - "db/migrate/20171010114644_create_memberships.rb"
    - "db/migrate/20171031131310_create_page_links.rb"
    - "db/migrate/20190603100709_create_join_table_areas_initiatives.rb"
    - "db/migrate/20190603100803_create_join_table_initiatives_topics.rb"
    - "db/migrate/20191210205216_create_id_cards.id_id_card_lookup.rb"
    - "db/migrate/20191218161144_create_unsubscription_tokens.email_campaigns.rb"
    - "db/migrate/20200807132541_create_common_passwords.rb"
    - "db/migrate/20210619133856_create_zeroshot_classification_tables.insights.rb"

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/SharedContext:
  Exclude:
    - "**/spec/acceptance/**/*"

RSpec/ImplicitSubject:
  Exclude:
    - "**/spec/policies/**/*"

Style/IfUnlessModifier:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  # We need a discussion on this because we have 347 offences against the default
  # and 252 offences against "EnforcedStyle: indented".
  EnforcedStyle: indented

RSpec/DescribeClass:
  IgnoredMetadata:
    type: ["request"]
  Exclude:
    - 'engines/commercial/id_bosa_fas/spec/requests/bosa_fas_verification_spec.rb'
    - 'engines/commercial/id_clave_unica/spec/requests/clave_unica_verification_spec.rb'
    - 'engines/commercial/id_franceconnect/spec/requests/franceconnect_verification_spec.rb'
    - 'engines/commercial/id_vienna_saml/spec/requests/citizen_authentication_spec.rb'
    - 'engines/commercial/id_vienna_saml/spec/requests/employee_authentication_spec.rb'
    - 'spec/requests/google_authentication_spec.rb'
    - 'engines/commercial/multi_tenancy/spec/db/seedfile_spec.rb'
    - 'engines/commercial/multi_tenancy/spec/tasks/email_campaigns_task_spec.rb'
    - 'engines/commercial/multi_tenancy/spec/tasks/fix_notifications_task_spec.rb'
    - 'engines/commercial/multi_tenancy/spec/tasks/invalid_data_checker_task_spec.rb'
    - 'spec/tasks/single_use/*.ignore.rb'

RSpec/EmptyExampleGroup:
  # `context` and `describe` are found as empty example groups when
  # `example_request`, `post`, etc are used, so exclude acceptance tests.
  Exclude:
    - "**/spec/acceptance/**/*"

RSpec/ExampleLength:
  Enabled: false

RSpec/SpecFilePathSuffix:
  Exclude:
    - 'spec/migrations/20241127093339_add_first_published_at_to_admin_publications_spec.ignore.rb'
    - 'spec/tasks/single_use/*.ignore.rb'

Metrics/MethodLength:
  Max: 61
  CountAsOne: ["array", "hash", "heredoc"]
  Exclude:
    - "**/db/migrate/**/*"

Lint/Void:
  Exclude:
    - "engines/commercial/multi_tenancy/config/initializers/sentry.rb"

Rails/UnknownEnv:
  # config/initializers/apartment.rb refers to staging, which is not part of the default settings.
  Environments: [development, test, production, staging]

# ==============================================================================
# Project-wide Style and Architecture Decisions
# ==============================================================================
# The following cops are disabled project-wide because they represent
# intentional architectural or style decisions with high offense counts.
# These are not temporary todos - they reflect how the codebase is structured.

# ------------------------------------------------------------------------------
# Line Length
# ------------------------------------------------------------------------------
Layout/LineLength:
  # 2945 offenses - project-wide decision about acceptable line length
  Max: 1269

# ------------------------------------------------------------------------------
# Metrics - Complexity and Size Thresholds
# ------------------------------------------------------------------------------
# These thresholds reflect the complexity of the domain and are acceptable
# for this codebase given the business logic requirements.

Metrics/AbcSize:
  Max: 126

Metrics/BlockNesting:
  Max: 5

Metrics/ClassLength:
  Max: 564

Metrics/CyclomaticComplexity:
  Max: 26

Metrics/ModuleLength:
  Max: 102

Metrics/ParameterLists:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 28

# ------------------------------------------------------------------------------
# RSpec Testing Style Preferences
# ------------------------------------------------------------------------------
# These represent intentional testing patterns used throughout the codebase.

RSpec/AnyInstance:
  # 119 offenses - sometimes necessary for testing complex dependencies
  Enabled: false

RSpec/ContextWording:
  # 1014 offenses - context descriptions don't need to follow strict prefix rules
  Enabled: false

RSpec/FilePath:
  # 197 offenses - spec file paths don't need to mirror implementation paths exactly
  Enabled: false

RSpec/IndexedLet:
  # 481 offenses - indexed let variables (let1, let2) are acceptable
  Enabled: false

RSpec/InstanceVariable:
  # 502 offenses - instance variables in tests are a common pattern
  Enabled: false

RSpec/LetSetup:
  # 450 offenses - let! for setup is an intentional pattern
  Enabled: false

RSpec/MessageSpies:
  # 307 offenses - both receive and have_received styles are acceptable
  Enabled: false

RSpec/MissingExampleGroupArgument:
  # 247 offenses - example groups without explicit subjects are acceptable
  Enabled: false

RSpec/NestedGroups:
  # Allow up to 6 levels of nesting for complex test scenarios
  Max: 6

RSpec/SpecFilePathFormat:
  # 184 offenses - spec file path format is flexible
  Enabled: false

RSpec/StubbedMock:
  # 77 offenses - stubbing and mocking in same example is sometimes necessary
  Enabled: false

RSpecRails/NegationBeValid:
  # 121 offenses - both not_to and be_invalid styles are acceptable
  Enabled: false

# ------------------------------------------------------------------------------
# FactoryBot Patterns
# ------------------------------------------------------------------------------

FactoryBot/AssociationStyle:
  # 73 offenses - both explicit and implicit association styles are acceptable
  Enabled: false

# ------------------------------------------------------------------------------
# Rails Patterns
# ------------------------------------------------------------------------------

Rails/BulkChangeTable:
  # 58 offenses - many old migrations don't use bulk change, not worth fixing
  Enabled: false

Rails/FindEach:
  # 150 offenses - .each is sometimes intentional for small collections
  Enabled: false

Rails/RedundantActiveRecordAllMethod:
  # 66 offenses - explicit .all is sometimes clearer
  Enabled: false

Rails/RedundantPresenceValidationOnBelongsTo:
  # 48 offenses - explicit presence validation on belongs_to is acceptable
  Enabled: false

Rails/ReversibleMigration:
  # 81 offenses - many data migrations are not reversible, which is acceptable
  Enabled: false

Rails/SkipsModelValidations:
  # 176 offenses - skipping validations is sometimes necessary for performance
  Enabled: false

Rails/TimeZone:
  # 371 offenses - Time usage patterns are acceptable
  Enabled: false

# ------------------------------------------------------------------------------
# Style Preferences
# ------------------------------------------------------------------------------

Style/ClassAndModuleChildren:
  # 475 offenses - both nested and compact class/module styles are acceptable
  Enabled: false

Style/MutableConstant:
  # 144 offenses - mutable constants are used intentionally
  Enabled: false

# ------------------------------------------------------------------------------
# Gemspec Configuration
# ------------------------------------------------------------------------------
# These are not relevant for internal engine gemspecs.

Gemspec/DevelopmentDependencies:
  # 86 offenses - development dependencies in gemspecs are acceptable
  Enabled: false

Gemspec/RequireMFA:
  # 46 offenses - MFA requirement not applicable for internal engines
  Enabled: false

Gemspec/RequiredRubyVersion:
  # 47 offenses - Ruby version not required in all gemspecs
  Enabled: false

# ------------------------------------------------------------------------------
# Security
# ------------------------------------------------------------------------------

Security/Open:
  # 37 offenses - many legitimate uses of Kernel.open and URI.open
  Enabled: false

# ------------------------------------------------------------------------------
# Naming Conventions
# ------------------------------------------------------------------------------

Naming/MethodParameterName:
  # 39 offenses - short parameter names are sometimes appropriate
  Enabled: false
