source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

gem 'rbtrace'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.3.5'
# Use postgresql as the database for Active Record
gem 'pg' # , '~> 0.18'
# Use Puma as the app server
gem 'puma', '~> 4.3.8'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'pry-byebug'
  gem 'database_cleaner'
  gem 'factory_bot_rails'
  gem 'license_finder'
  gem 'rack-mini-profiler'
  gem 'rspec_api_documentation'
  gem 'rspec_junit_formatter'
  gem 'rspec-rails'
  gem 'rspec-parameterized'
  gem 'rubocop-ast', '~> 0.7.1', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'simplecov'
  gem 'simplecov-rcov'
  gem "test-prof", "~> 1.0"
end

group :development do
  gem 'bullet'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'pry'
  gem 'pry-stack_explorer'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'redcarpet'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'rubyXL'
  gem 'shoulda-matchers', '~> 3.1'
  gem 'webmock', '~> 3.12'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Latest version (2.4.1) of Pundit on RubyGems is quite outdated (2019-08-14).
# This newer version from Git adds reason to Pundit::NotAuthorized.
gem "pundit", git: 'https://github.com/varvet/pundit', branch: 'master', ref: '973b63b396c2a98099caf5eefd1c6841416eddfa'
gem "active_model_serializers", "~> 0.10.8"

# See https://github.com/nsarno/knock/issues/250
# Installs v2.2 which is not available on rubygems.org
gem 'knock', git: 'https://github.com/nsarno/knock', branch: 'master', ref: '9214cd027422df8dc31eb67c60032fbbf8fc100b'
gem 'que', git: 'https://github.com/que-rb/que', branch: 'master', ref: '77c6b92952b821898c393239ce0e4047b17d7dae'
gem 'que-web'

gem 'activerecord-import', '~> 1.0'
gem 'activerecord_json_validator', '~> 1.3.0'
gem 'activerecord-postgis-adapter', '~> 6.0.0'

gem 'api-pagination', '~> 4.8.2'
gem 'carrierwave', '~> 2.2.0'
gem 'carrierwave-base64', '~> 2.8.1'
gem 'kaminari', '~> 1.2'

gem 'rails-i18n', '~> 6.0.0'

gem 'awesome_nested_set', '~> 3.4.0'
gem 'axlsx', '3.0.0.pre'
gem 'counter_culture', '~> 2.8'
gem 'fog-aws'
gem 'groupdate' # , "~> 3.2.0"
gem 'interactor'
gem 'interactor-rails'
gem 'liquid', '~> 4.0'
gem 'mini_magick', '~> 4.9'
gem 'pg_search', '~> 2.3.5'
gem 'premailer-rails', '~> 1.10.3'
gem 'rest-client'
gem 'rgeo-geojson'
gem 'rubyzip', '~> 1.3.0'

gem 'okcomputer'
gem 'omniauth', '~> 1.9.1'
gem 'omniauth-rails_csrf_protection'
gem 'omniauth-facebook'
gem 'omniauth-google-oauth2'
gem 'sentry-raven'
gem 'simple_segment', '~>1.2'
# This fork was made to update the version of jws which is
# required for the google omniauth gem.
gem 'omniauth-azure-activedirectory', github: 'CitizenLabDotCo/omniauth-azure-activedirectory'
gem 'omniauth_openid_connect', '~> 0.3.3'
# Forked to support a userinfo response in JWT form
# Can go back to vanilla when this PR is merged and released:
# https://github.com/nov/openid_connect/pull/48
gem 'acts_as_list'
gem 'bunny', '>= 2.7.2'
gem 'faker'
gem 'order_as_specified'
gem 'openid_connect', github: 'CitizenLabDotCo/openid_connect'
gem 'scenic'

# This fork was made to support the latest verions of Ruby
# and Rails.
gem 'ice_cube', github: 'CitizenLabDotCo/ice_cube'
# Also required here to be able to initialize Mailgun in
# e.g. production.rb, which would otherwise result in an
# "undefined method 'mailgun_settings=' for ActionMailer::Base:Class"
# exception.
gem 'aws-sdk-s3', '~> 1'
gem 'bootsnap', require: false
gem 'dalli'
gem 'mailgun-ruby', '~>1.2.0'
gem 'rails_semantic_logger'
gem 'rinku', '~> 2'
# For serialization of heterogeneous collections (i.e. notifications), see
# https://github.com/Netflix/fast_jsonapi/pull/410.
gem 'fast_jsonapi', github: 'dvandersluis/fast_jsonapi', branch: 'heterogeneous-collection'
gem 'rack-attack', '~> 6'

# mjml-rails cannot find the MJML parser when installed
# through the emails engine and is therefore specified
# in the main app.
gem 'intercom', '~> 4.1'
gem 'mjml-rails', '~> 4.4'

require 'json'
if File.exists?('../citizenlab.config.ee.json')
  # This branch must be used because the latest version (2.1.1)
  # requires activerecord < 6.0.
  gem 'apartment', github: 'influitive/apartment', branch: 'development'
end

require './lib/citizen_lab.rb'
CitizenLab.enabled_modules.each do |m|
  if File.exists?("engines/#{m}")
    gem m.split('/').last, path: "engines/#{m}"
  end
end
