# frozen_string_literal: true

require 'rails_helper'

describe BulkImportIdeas::Parsers::Pdf::IdeaHtmlPdfPlainTextParser do
  describe 'parse_text' do
    let(:raw_text_array) do
      ["go\nvocal\nFormerly\nCitizenLab\nWelcome to our survey\nFill it in as honestly as you can. We've customised this introduction - so please:\n1. Don't lie\n2. Be nice\nPersonal data\nWe will submit your input to Abshireville's online participation platform. If you want to\nreceive updates relevant to your input by email, please fill out the following fields on\nthis page and we will create an account for you. Your data will not be public and will\nonly be used by Abshireville. If you do not agree for us to use your personal data in this\nway, you can leave them empty.\nFirst name(s) (optional)\nJames\nLast name (optional)\nSmith\nEmail address (optional)\nJames @monkey.org\nBy checking this box I consent to my data being used to create an account on\nAbshireville's participation platform.\nPage 1\n",
        "This is a page title\nAnd here is the description of it. These appear as section dividers and not new pages in\nthe printed form.\n1. Your question (optional)\n& Option 1\n○ Option 2\n2. This is a short answer (optional)\nI really like Short\nanswers\n3. This is a long answer (optional)\nInstructions\n• Put whatever you want here\nI'm\nThey\nnot so\nmuch longer\nKeen\nол\nanswers.\nLong\nto\ntake\nFill in\nThis is another page title\nBut this is just a section in the printed version, not a single page.\n4. Linear scale field (optional)\nWith a description....\nPlease write a number between 1 and 5 only\n1\n5. Another linear scale - no description (optional)\nPlease write a number between 1 (Totally worst) and 7 (Absolute best) only\n2\nPage 2\n",
        "6. Multiple choice (optional)\n*Choose as many as you like\n☐ this one\n☑ another option you might like more\n☑ something else\nIf 'something else', please specify\nI cannot\nmake up my\nmy mind\n7. Image choice (optional)\n*Choose between 2 and 4 options\n☐ Choose Marge\n☐ Choose bart\n☑ Choose homer\nPO\nG\n☐ All the Simpsons\n☐ Choose Lisa\n☑ Choose Maggie\n☑ Other\nIf 'Other', please specify\nSeymour\nPage 3\n",
        "8. Ranking question (optional)\nPlease write a number from 1 (most preferred) and 3 (least preferred) in each\nbox. Use each number only once.\n2 First one\n1 Another one\n3 Choose this one\n9. Rating question (optional)\nRate this by writing a number between 1 (worst) and 5 (best).\n3\n10. Sentiment scale question (optional)\nPlease write a number between 1 and 5.\n1 = Very bad, 3 = Ok, 5 = Very good.\n5\n11. Matrix question (optional)\nFor each row, mark one circle with a cross to indicate your preference.\nStrongly\nStrongly\ndisagree\nDisagree Neutral\nAgree\nagree\nI like stuff\n0\n&\nO\n0\nI like nonsense\n0\n0\ns\n0\n0\nI like nothing, but I do\nlike really long\nstatements as they\nare the best!\n0\nO\n0\nØ\n0\n12. File upload field (optional)\nThis field cannot be completed on paper. Please use the online version of this\nform instead.\n13. Number field (optional)\n283\nPage 4\n",
        "Mapping page\nAll the questions in this section relate to the following map.\nHIGH\n無用銀行:\nmang\nMYLOR \nROAD\nmares殊是問題\n080\nT\nの場\nGISB\na\n92%\nANSELL ROAD\nHIGHCLIFFE ROAD\nte\ng\nDOBBIN HILLDOPPIN\n*\nFALKLAND ROAD\nNEE.\nHIGH STORRS ROAD\nS\nM\n70\nEDALE ROAD\nBRA\nRINGINGLOW ROA\nmm\nawwa\nB\nmegy on\nR\npu\nWoman wRINGINGLOW \nROAD\n4\n麵類蜜集 衛\n#\nSA\n8\nHOOBER\n845\nRINGINGLOW ROAD\nMapTiler OpenStreetMap contributors\n14. Drop pin question (optional)\nPlease do something with this map\nPlease draw an X on the map below to show the location or write the address\ninstead.\nRue de\n10\nFromage\nWoluwe-Sair\nLambert-Si\nLambrechts\nWoluwe\nDilbeek\nBruxelles Brussel\nItterbeek\nAnderlecht\nEtterbeek\nIxelles\nElsene\ntrudis-\nle\nSaint-Gilles\n-Sint-Gillis\nAa\n☑\nAuderghei\n-Ouderge\nSobroek\nForest-Vorst\nVlezenbeek\nNegenmanneke\nUccle - Ukkel\nWatermael-\nBoitsfort-\nWatermaal-\nBosvoorde\nZuun\nRuisbroek\nSint-Pieters-\nLeeuw\nLinkebeek\nMapTiler OpenStreetMap contributors.\nBeersel\nPage 5\n",
        "15. Draw route question (optional)\nDraw sometning\nPlease draw a route on the map below.\nEvere\nGanshoren\nSchaerbeek-\nSchaarbeek\nem-\ngathe\ngatha-\nem\nKoekelberg\nMolenbeek-\nSaint-Jean\n-Sint-Jans-\nMolenbeek\nSaint-Josse-\nten-Noode\n-Sint-Joost-\nten-Node\nBruxelles- Brussel\nAnderlecht\nEtterbeek\nIxelles-\nElsene\nMapTiler OpenStreetMap contributors\n16. Draw area question (optional)\nDraw an area please\nPlease draw a shape on the map below.\nEvere\nGanshoren\nem-\nSchaerbeek-\nSchaarbeek\ngathe\njatha-\nem\nKoekelberg\nt\nMolenbeek-\nMolenbeek\nSaint-Josse-\nten-Noode\n-Sint-Joost-\nten-Node\nBruxelles- Brussel\nAnderlecht\nEtterbeek\nIxelles-\nElsene\nMapTiler OpenStreetMap contributors\nPage 6\n",
        "About you\n17. Gender (optional)\n☑ Male\n○ Female\nOther\n18. Year of birth (optional)\n1976\n19. Are you a politician? (optional)\nWe use this to provide you with customized information\nO Active politician\n☑ Retired politician\nO No\n20. Place of residence (optional)\nO Herbland\nWest Horacio\nO West Rexberg\n○ Murielport\nO Candiestad\nO North Hisakoland\n○ Boehmshire\n☑ Oscarburgh\nO Jonathanfort\nRoweview\n○ East Jackelineport\n○ North Reyberg\n○ Westbrook\nO Somewhere else\nThanks for filling in this printed survey\nWe will use your answers to make wise decisions.\n.\nPage 7\n"]
    end

    let(:template_data) do
      { page_count: 7,
        fields: [{ name: 'Your question',
                   type: 'field',
                   key: 'your_question_6l0',
                   page: 2,
                   position: 10,
                   input_type: 'select',
                   is_number: false,
                   code: nil,
                   description: nil,
                   print_title: '1. Your question (optional)',
                   print_format: :single_select,
                   content_delimiters: { start: 'Option 2', end: '2. This is a short answer (optional)' } },
          { name: 'Option 1', type: 'option', key: 'option_1_m9p', page: 2, position: 14, parent_key: 'your_question_6l0' },
          { name: 'Option 2', type: 'option', key: 'option_2_fpd', page: 2, position: 16, parent_key: 'your_question_6l0' },
          { name: 'This is a short answer',
            type: 'field',
            key: 'this_is_a_short_answer_o7i',
            page: 2,
            position: 21,
            input_type: 'text',
            is_number: false,
            code: nil,
            description: nil,
            print_title: '2. This is a short answer (optional)',
            print_format: :single_line_text,
            content_delimiters: { start: '2. This is a short answer (optional)', end: '3. This is a long answer (optional)' } },
          { name: 'This is a long answer',
            type: 'field',
            key: 'this_is_a_long_answer_j4k',
            page: 2,
            position: 29,
            input_type: 'multiline_text',
            is_number: false,
            code: nil,
            description: 'InstructionsPut whatever you want here',
            print_title: '3. This is a long answer (optional)',
            print_format: :multi_line_text,
            content_delimiters: { start: 'Put whatever you want here', end: 'This is another page title' } },
          { name: 'Linear scale field',
            type: 'field',
            key: 'linear_scale_field_fq5',
            page: 2,
            position: 74,
            input_type: 'linear_scale',
            is_number: true,
            code: nil,
            description: 'With a description....',
            print_title: '4. Linear scale field (optional)',
            print_format: :single_line_text,
            content_delimiters: { start: 'Please write a number between 1 and 5 only', end: '5. Another linear scale - no description (optional)' } },
          { name: 'Another linear scale - no description',
            type: 'field',
            key: 'another_linear_scale_jul',
            page: 2,
            position: 88,
            input_type: 'linear_scale',
            is_number: true,
            code: nil,
            description: nil,
            print_title: '5. Another linear scale - no description (optional)',
            print_format: :single_line_text,
            content_delimiters: { start: 'i        i   (          )', end: '6. Multiple choice (optional)' } },
          { name: 'Multiple choice',
            type: 'field',
            key: 'multiple_choice_fyh',
            page: 3,
            position: 2,
            input_type: 'multiselect',
            is_number: false,
            code: nil,
            description: nil,
            print_title: '6. Multiple choice (optional)',
            print_format: :multi_select,
            content_delimiters: { start: 'i          i   (         )', end: "If 'something else', please specify" } },
          { name: 'this one', type: 'option', key: 'this_one_t3a', page: 3, position: 6, parent_key: 'multiple_choice_fyh' },
          { name: 'another option you might like more', type: 'option', key: 'another_option_you_might_like_more_na7', page: 3, position: 10, parent_key: 'multiple_choice_fyh' },
          { name: 'something else', type: 'option', key: 'other', page: 3, position: 11, parent_key: 'multiple_choice_fyh' },
          { name: "If 'something else', please specify",
            type: 'field',
            key: 'multiple_choice_fyh_other',
            page: 3,
            position: 16,
            input_type: 'text',
            is_number: false,
            code: nil,
            description: nil,
            print_title: "If 'something else', please specify",
            print_format: :single_line_text,
            content_delimiters: { start: 'i          i   (         )', end: 'Image choice (optional)' } },
          { name: 'Image choice',
            type: 'field',
            key: 'image_choice_9z2',
            page: 3,
            position: 26,
            input_type: 'multiselect_image',
            is_number: false,
            code: nil,
            description: nil,
            print_title: '7. Image choice (optional)',
            print_format: :multi_select_image,
            content_delimiters: { start: 'i          i   (         )', end: "If 'Other', please specify" } },
          { name: 'Choose bart', type: 'option', key: 'choose_bart_wjv', page: 3, position: 45, parent_key: 'image_choice_9z2' },
          { name: 'Choose Lisa', type: 'option', key: 'choose_lisa_jzm', page: 3, position: 63, parent_key: 'image_choice_9z2' },
          { name: 'Other', type: 'option', key: 'other', page: 3, position: 81, parent_key: 'image_choice_9z2' },
          { name: "If 'Other', please specify",
            type: 'field',
            key: 'image_choice_9z2_other',
            page: 3,
            position: 85,
            input_type: 'text',
            is_number: false,
            code: nil,
            description: nil,
            print_title: "If 'Other', please specify",
            print_format: :single_line_text,
            content_delimiters: { start: 'i          i   (         )', end: 'Ranking question (optional)' } },
          { name: 'First one', type: 'option', key: 'first_one_nzc', page: 4, position: 10, parent_key: 'ranking_question_7k9' },
          { name: 'Another one', type: 'option', key: 'another_one_l3z', page: 4, position: 13, parent_key: 'ranking_question_7k9' },
          { name: 'Choose this one', type: 'option', key: 'choose_this_one_rpq', page: 4, position: 16, parent_key: 'ranking_question_7k9' },
          { name: 'Rating question',
            type: 'field',
            key: 'rating_q_s7h',
            page: 4,
            position: 22,
            input_type: 'rating',
            is_number: true,
            code: nil,
            description: nil,
            print_title: '9. Rating question (optional)',
            print_format: :single_line_text,
            content_delimiters: { start: 'Rate this by writing a number between 1 (worst) and 5 (best).', end: '10. Sentiment scale question (optional)' } },
          { name: 'Sentiment scale question',
            type: 'field',
            key: 'sentiment_scale_question_puz',
            page: 4,
            position: 33,
            input_type: 'sentiment_linear_scale',
            is_number: true,
            code: nil,
            description: nil,
            print_title: '10. Sentiment scale question (optional)',
            print_format: :single_line_text,
            content_delimiters: { start: '1 = Very bad, 3 = Ok, 5 = Very good.', end: '11. Matrix question (optional)' } },
          { name: 'Number field',
            type: 'field',
            key: 'number_field_eon',
            page: 4,
            position: 83,
            input_type: 'number',
            is_number: true,
            code: nil,
            description: nil,
            print_title: '13. Number field (optional)',
            print_format: :single_line_text,
            content_delimiters: { start: 'i', end: 'Mapping page (optional)' } },
          { name: 'Gender',
            type: 'field',
            key: 'u_gender',
            page: 7,
            position: 6,
            input_type: 'select',
            is_number: false,
            code: nil,
            description: nil,
            print_title: '17. Gender (optional)',
            print_format: :single_select,
            content_delimiters: { start: 'Other', end: '18. Year of birth (optional)' } },
          { name: 'Male', type: 'option', key: 'male', page: 7, position: 10, parent_key: 'u_gender' },
          { name: 'Female', type: 'option', key: 'female', page: 7, position: 11, parent_key: 'u_gender' },
          { name: 'Other', type: 'option', key: 'unspecified', page: 3, position: 85, parent_key: 'u_gender' },
          { name: 'Year of birth',
            type: 'field',
            key: 'u_birthyear',
            page: 7,
            position: 19,
            input_type: 'number',
            is_number: true,
            code: nil,
            description: nil,
            print_title: '18. Year of birth (optional)',
            print_format: :single_line_text,
            content_delimiters: { start: '18. Year of birth (optional)', end: '19. Are you a politician? (optional)' } },
          { name: 'Are you a politician?',
            type: 'field',
            key: 'u_politician',
            page: 7,
            position: 27,
            input_type: 'select',
            is_number: false,
            code: nil,
            description: 'We use this to provide you with customized information',
            print_title: '19. Are you a politician? (optional)',
            print_format: :single_select,
            content_delimiters: { start: 'We will use your answers to make wise decisions.', end: '20. Place of residence (optional)' } },
          { name: 'Active politician', type: 'option', key: 'active_politician', page: 7, position: 32, parent_key: 'u_politician' },
          { name: 'Retired politician', type: 'option', key: 'retired_politician', page: 7, position: 35, parent_key: 'u_politician' },
          { name: 'No', type: 'option', key: 'no', page: 7, position: 37, parent_key: 'u_politician' },
          { name: 'Herbland', type: 'option', key: 'herbland_h76', page: 7, position: 44, parent_key: 'u_domicile' },
          { name: 'West Horacio', type: 'option', key: 'west_horacio_y0z', page: 7, position: 48, parent_key: 'u_domicile' },
          { name: 'West Rexberg', type: 'option', key: 'west_rexberg_nkg', page: 7, position: 49, parent_key: 'u_domicile' },
          { name: 'Murielport', type: 'option', key: 'murielport_oic', page: 7, position: 51, parent_key: 'u_domicile' },
          { name: 'Candiestad', type: 'option', key: 'candiestad_kyl', page: 7, position: 54, parent_key: 'u_domicile' },
          { name: 'North Hisakoland', type: 'option', key: 'north_hisakoland_9f3', page: 7, position: 56, parent_key: 'u_domicile' },
          { name: 'Boehmshire', type: 'option', key: 'boehmshire_jo2', page: 7, position: 59, parent_key: 'u_domicile' },
          { name: 'Oscarburgh', type: 'option', key: 'oscarburgh_rsw', page: 7, position: 60, parent_key: 'u_domicile' },
          { name: 'Jonathanfort', type: 'option', key: 'jonathanfort_vw9', page: 7, position: 63, parent_key: 'u_domicile' },
          { name: 'Roweview', type: 'option', key: 'roweview_kar', page: 7, position: 65, parent_key: 'u_domicile' },
          { name: 'East Jackelineport', type: 'option', key: 'east_jackelineport_roh', page: 7, position: 67, parent_key: 'u_domicile' },
          { name: 'North Reyberg', type: 'option', key: 'north_reyberg_j4t', page: 7, position: 70, parent_key: 'u_domicile' },
          { name: 'Westbrook', type: 'option', key: 'westbrook_cd0', page: 7, position: 71, parent_key: 'u_domicile' },
          { name: 'Somewhere else', type: 'option', key: 'somewhere_else_41w', page: 7, position: 75, parent_key: 'u_domicile' }] }
    end

    it 'extracts the data' do
      service = described_class.new
      service.parse_text(raw_text_array, template_data)
      binding.pry

      # TODO: NOW NEED TO GET THE LATEST template_data and check all the options are there
      expect(result[:fields].size).to eq 20
      # expect(result[:fields]['1. Your question']).to eq 'Option 1'
      # expect(result[:fields]['2. This is a short answer']).to eq 'I really like Short answers'
      # expect(result[:fields]['3. This is a long answer']).to eq "I'm\nThey\nnot so\nmuch longer\nKeen\nол\nanswers."
      # expect(result[:fields]['4. Linear scale field']).to eq 1
      # expect(result[:fields]['5. Another linear scale- no description']).to eq 2
      # expect(result[:fields]['6. Multiple choice']).to match_array %w[this one another option you might like more something else]
      # expect(result[:fields]['7. Image choice']).to match_array %w[Choose Marge Choose bart Choose homer All the Simpsons Choose Lisa Choose Maggie]
      # expect(result[:fields]['8. Ranking question']).to match_array %w[First one Another one Choose this one]
      # expect(result[:fields]['9. Rating question']).to eq 3
      # expect(result[:fields]['10. Sentiment scale question']).to eq 5
      # expect(result[:fields]['13. Number field']).to eq 283
    end
  end
end
