# frozen_string_literal: true

CONFIRMATION_CODE_PATTERN = /\A[a-zA-Z0-9]{12}\z/i
LEGACY_CONFIRMATION_CODE_PATTERN = /\A[0-9]{4}\z/i
VALID_USER_CONFIRMATION_CODE_PATTERNS = /\A(#{CONFIRMATION_CODE_PATTERN}|#{LEGACY_CONFIRMATION_CODE_PATTERN})\z/
