export const PROJECTABLE_HEADER_BG_ASPECT_RATIO_WIDTH = 4;
export const PROJECTABLE_HEADER_BG_ASPECT_RATIO_HEIGHT = 1;
export const PROJECTABLE_HEADER_BG_ASPECT_RATIO =
  PROJECTABLE_HEADER_BG_ASPECT_RATIO_WIDTH /
  PROJECTABLE_HEADER_BG_ASPECT_RATIO_HEIGHT;
