export const ACTION_PREFIX = 'ADMIN/USERS/INDEX';

export const SEARCH_TERM_CHANGED = 'ADMIN/USERS/INDEX/SEARCH_TERM_CHANGED';
export const PAGE_SELECTION_CHANGED = 'ADMIN/USERS/INDEX/PAGE_SELECTION_CHANGED';
export const SORT_COLUMN_CHANGED = 'ADMIN/USERS/INDEX/SORT_COLUMN_CHANGED';
export const INITIAL_LOAD = 'ADMIN/USERS/INDEX/INITIAL_LOAD';

export const LOAD_USERS_XLSX_REQUEST = 'app/Admin/USERS/LOAD_USERS_XLSX_REQUEST';
export const LOAD_USERS_XLSX_SUCCESS = 'app/Admin/USERS/LOAD_USERS_XLSX_SUCCESS';
export const LOAD_USERS_XLSX_ERROR = 'app/Admin/USERS/LOAD_USERS_XLSX_ERROR';
