files:
  - source: /app/translations/en.json
    translation: /app/translations/%locale%.json
    languages_mapping:
      locale:
        en: en
        no: nb-NO
    update_option: update_without_changes
