// store
export const UPDATE_CURRENT_USER_REQUEST = 'app/UsersEditPage/UPDATE_CURRENT_USER_REQUEST';
export const UPDATE_CURRENT_USER_SUCCESS = 'app/UsersEditPage/UPDATE_CURRENT_USER_SUCCESS';
export const UPDATE_CURRENT_USER_ERROR = 'app/UsersEditPage/UPDATE_CURRENT_USER_ERROR';
