// store
export const UPDATE_CURRENT_USER_REQUEST = 'user.update.UPDATE_CURRENT_USER_REQUEST';
export const UPDATE_CURRENT_USER_SUCCESS = 'user.update.UPDATE_CURRENT_USER_SUCCESS';
export const UPDATE_CURRENT_USER_ERROR = 'user.update.UPDATE_CURRENT_USER_ERROR';

export const COMPLETE_USER_REGISTRATION = 'user.update.COMPLETE_USER_REGISTRATION';
