import React from 'react';

import { Box } from '@citizenlab/cl2-component-library';

// import useHomepageLayout from 'api/home_page_layout/useHomepageLayout';

import Editor from 'containers/Admin/pagesAndMenu/containers/ContentBuilder/components/Editor';

import { IMAGES_LOADED_EVENT } from 'components/admin/ContentBuilder/constants';
import ContentBuilderFrame from 'components/admin/ContentBuilder/Frame';

import eventEmitter from 'utils/eventEmitter';

const a = {
  ROOT: {
    type: 'div',
    nodes: ['HOMEPAGEBANNER', 'PROJECTS'],
    props: {
      id: 'e2e-content-builder-frame',
    },
    custom: {},
    hidden: false,
    isCanvas: true,
    displayName: 'div',
    linkedNodes: {},
  },
  PROJECTS: {
    type: {
      resolvedName: 'Projects',
    },
    nodes: [],
    props: {
      currentlyWorkingOnText: {
        en: '',
        mi: '',
        'ar-MA': '',
        'ar-SA': '',
        'ca-ES': '',
        'cy-GB': '',
        'da-DK': '',
        'de-DE': '',
        'el-GR': '',
        'en-CA': '',
        'en-GB': '',
        'en-IE': '',
        'es-CL': '',
        'es-ES': '',
        'fi-FI': '',
        'fr-BE': '',
        'fr-FR': '',
        'hr-HR': '',
        'hu-HU': '',
        'it-IT': '',
        'kl-GL': '',
        'lb-LU': '',
        'lv-LV': '',
        'nb-NO': '',
        'nl-BE': '',
        'nl-NL': '',
        'pl-PL': '',
        'pt-BR': '',
        'ro-RO': '',
        'sr-SP': '',
        'sv-SE': '',
        'tr-TR': '',
        'sr-Latn': '',
      },
    },
    custom: {
      title: {
        id: 'app.containers.Admin.pagesAndMenu.containers.ContentBuilder.components.CraftComponents.Projects.projectsTitle',
        defaultMessage: 'Projects',
      },
      noDelete: true,
      noPointerEvents: true,
    },
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'Projects',
    linkedNodes: {},
  },
  HOMEPAGEBANNER: {
    type: {
      resolvedName: 'HomepageBanner',
    },
    nodes: [],
    props: {
      image: {
        dataCode: '21e802c0-ba07-409c-b34a-ea9c6e22d74e',
        imageUrl:
          'http://localhost:4000/uploads/41b880d9-f267-4cc6-8031-bcf7b66e8fc4/content_builder/layout_image/image/598ea7af-106c-488c-91b5-bfb54e94c05e/69bad434-aaf0-41f1-82c1-555e33bb2c7b.jpg',
      },
      errors: [],
      hasError: false,
      homepageSettings: {
        banner_layout: 'full_width_banner_layout',
        banner_avatars_enabled: true,
        banner_cta_signed_in_url: '',
        banner_cta_signed_in_type: 'no_button',
        banner_cta_signed_out_url: '',
        banner_cta_signed_out_type: 'sign_up_button',
        banner_signed_in_header_multiloc: {
          en: '',
          mi: '',
          'ar-MA': '',
          'ar-SA': '',
          'ca-ES': '',
          'cy-GB': '',
          'da-DK': '',
          'de-DE': '',
          'el-GR': '',
          'en-CA': '',
          'en-GB': '',
          'en-IE': '',
          'es-CL': '',
          'es-ES': '',
          'fi-FI': '',
          'fr-BE': '',
          'fr-FR': '',
          'hr-HR': '',
          'hu-HU': '',
          'it-IT': '',
          'kl-GL': '',
          'lb-LU': '',
          'lv-LV': '',
          'nb-NO': '',
          'nl-BE': '',
          'nl-NL': '',
          'pl-PL': '',
          'pt-BR': '',
          'ro-RO': '',
          'sr-SP': '',
          'sv-SE': '',
          'tr-TR': '',
          'sr-Latn': '',
        },
        banner_signed_out_header_multiloc: {
          en: '',
          mi: '',
          'ar-MA': '',
          'ar-SA': '',
          'ca-ES': '',
          'cy-GB': '',
          'da-DK': '',
          'de-DE': '',
          'el-GR': '',
          'en-CA': '',
          'en-GB': '',
          'en-IE': '',
          'es-CL': '',
          'es-ES': '',
          'fi-FI': '',
          'fr-BE': '',
          'fr-FR': '',
          'hr-HR': '',
          'hu-HU': '',
          'it-IT': '',
          'kl-GL': '',
          'lb-LU': '',
          'lv-LV': '',
          'nb-NO': '',
          'nl-BE': '',
          'nl-NL': '',
          'pl-PL': '',
          'pt-BR': '',
          'ro-RO': '',
          'sr-SP': '',
          'sv-SE': '',
          'tr-TR': '',
          'sr-Latn': '',
        },
        banner_cta_signed_in_text_multiloc: {
          en: '',
          mi: '',
          'ar-MA': '',
          'ar-SA': '',
          'ca-ES': '',
          'cy-GB': '',
          'da-DK': '',
          'de-DE': '',
          'el-GR': '',
          'en-CA': '',
          'en-GB': '',
          'en-IE': '',
          'es-CL': '',
          'es-ES': '',
          'fi-FI': '',
          'fr-BE': '',
          'fr-FR': '',
          'hr-HR': '',
          'hu-HU': '',
          'it-IT': '',
          'kl-GL': '',
          'lb-LU': '',
          'lv-LV': '',
          'nb-NO': '',
          'nl-BE': '',
          'nl-NL': '',
          'pl-PL': '',
          'pt-BR': '',
          'ro-RO': '',
          'sr-SP': '',
          'sv-SE': '',
          'tr-TR': '',
          'sr-Latn': '',
        },
        banner_cta_signed_out_text_multiloc: {
          en: '',
          mi: '',
          'ar-MA': '',
          'ar-SA': '',
          'ca-ES': '',
          'cy-GB': '',
          'da-DK': '',
          'de-DE': '',
          'el-GR': '',
          'en-CA': '',
          'en-GB': '',
          'en-IE': '',
          'es-CL': '',
          'es-ES': '',
          'fi-FI': '',
          'fr-BE': '',
          'fr-FR': '',
          'hr-HR': '',
          'hu-HU': '',
          'it-IT': '',
          'kl-GL': '',
          'lb-LU': '',
          'lv-LV': '',
          'nb-NO': '',
          'nl-BE': '',
          'nl-NL': '',
          'pl-PL': '',
          'pt-BR': '',
          'ro-RO': '',
          'sr-SP': '',
          'sv-SE': '',
          'tr-TR': '',
          'sr-Latn': '',
        },
        banner_signed_out_subheader_multiloc: {
          en: '',
          mi: '',
          'ar-MA': '',
          'ar-SA': '',
          'ca-ES': '',
          'cy-GB': '',
          'da-DK': '',
          'de-DE': '',
          'el-GR': '',
          'en-CA': '',
          'en-GB': '',
          'en-IE': '',
          'es-CL': '',
          'es-ES': '',
          'fi-FI': '',
          'fr-BE': '',
          'fr-FR': '',
          'hr-HR': '',
          'hu-HU': '',
          'it-IT': '',
          'kl-GL': '',
          'lb-LU': '',
          'lv-LV': '',
          'nb-NO': '',
          'nl-BE': '',
          'nl-NL': '',
          'pl-PL': '',
          'pt-BR': '',
          'ro-RO': '',
          'sr-SP': '',
          'sv-SE': '',
          'tr-TR': '',
          'sr-Latn': '',
        },
        banner_signed_in_header_overlay_color: '#0A5159',
        banner_signed_out_header_overlay_color: '#0A5159',
        banner_signed_in_header_overlay_opacity: 90,
        banner_signed_out_header_overlay_opacity: 90,
      },
    },
    custom: {
      title: {
        id: 'app.containers.admin.ContentBuilder.homepage.homepageBanner',
        defaultMessage: 'Homepage banner',
      },
      noDelete: true,
      noPointerEvents: true,
    },
    hidden: false,
    parent: 'ROOT',
    isCanvas: false,
    displayName: 'HomepageBanner',
    linkedNodes: {},
  },
};

const handleLoadImages = () => {
  eventEmitter.emit(IMAGES_LOADED_EVENT);
};

const Preview = () => {
  // const { data: homepageLayout } = useHomepageLayout();

  // const homepageContent = homepageLayout?.data.attributes.craftjs_json;

  return (
    <Box>
      <Editor isPreview={true}>
        <ContentBuilderFrame
          editorData={a as any}
          onLoadImages={handleLoadImages}
        />
      </Editor>
    </Box>
  );
};

export default Preview;
