// renderers
import {
  linearScaleControlTester,
  LinearScaleControl,
  ratingControlTester,
  RatingControl,
  MapControl,
  mapControlTester,
  inputControlTester,
  InputControl,
  textAreaControlTester,
  TextAreaControl,
  multiSelectCheckboxControlTester,
  MultiSelectCheckboxControl,
  imageMultichoiceControlTester,
  ImageMultichoiceControl,
  singleSelectRadioControlTester,
  SingleSelectRadioControl,
  singleSelectRadioEnumControlTester,
  SingleSelectRadioEnumControl,
  WYSIWYGControlTester,
  WYSIWYGControl,
  descriptionControlTester,
  DescriptionControl,
  topicsControlTester,
  TopicsControl,
  titleControlTester,
  TitleControl,
  imageControlTester,
  ImageControl,
  attachmentsControlTester,
  AttachmentsControl,
  clPageTester,
  CLPageLayout,
  locationControlTester,
  LocationControl,
  dateControlTester,
  DateControl,
  userPickerControlTester,
  UserPickerControl,
  multilocInputTester,
  MultilocInputLayout,
  orderedLayoutTester,
  OrderedLayout,
  checkboxControlTester,
  singleSelectControlTester,
  SingleSelectEnumControlTester,
  SingleSelectEnumControl,
  CheckboxControl,
  MultiSelectControl,
  multiSelectControlTester,
  SingleSelectControl,
  singleAttachmentControlTester,
  SingleAttachmentControl,
  shapefileUploadControlTester,
  ShapefileUploadControl,
  CosponsorsControl,
  cosponsorsControlTester,
  rankingControlTester,
  MatrixControl,
  matrixControlTester,
  RankingControl,
  SentimentLinearScaleControl,
  sentimentLinearScaleControlTester,
} from 'components/Form/Components/Controls';

const commonRenderers = [
  { tester: linearScaleControlTester, renderer: LinearScaleControl },
  { tester: ratingControlTester, renderer: RatingControl },
  { tester: inputControlTester, renderer: InputControl },
  { tester: textAreaControlTester, renderer: TextAreaControl },
  { tester: checkboxControlTester, renderer: CheckboxControl },
  { tester: singleSelectControlTester, renderer: SingleSelectControl },
  { tester: SingleSelectEnumControlTester, renderer: SingleSelectEnumControl },
  { tester: multiSelectControlTester, renderer: MultiSelectControl },
  { tester: rankingControlTester, renderer: RankingControl },
  { tester: matrixControlTester, renderer: MatrixControl },
  { tester: WYSIWYGControlTester, renderer: WYSIWYGControl },
  { tester: descriptionControlTester, renderer: DescriptionControl },
  { tester: topicsControlTester, renderer: TopicsControl },
  { tester: titleControlTester, renderer: TitleControl },
  { tester: imageControlTester, renderer: ImageControl },
  { tester: attachmentsControlTester, renderer: AttachmentsControl },
  { tester: clPageTester, renderer: CLPageLayout },
  { tester: orderedLayoutTester, renderer: OrderedLayout },
  { tester: locationControlTester, renderer: LocationControl },
  { tester: dateControlTester, renderer: DateControl },
  { tester: userPickerControlTester, renderer: UserPickerControl },
  { tester: multilocInputTester, renderer: MultilocInputLayout },
  { tester: orderedLayoutTester, renderer: OrderedLayout },
  { tester: cosponsorsControlTester, renderer: CosponsorsControl },
  {
    tester: sentimentLinearScaleControlTester,
    renderer: SentimentLinearScaleControl,
  },
];

export const selectRenderers = (formType: 'default' | 'input' | 'survey') => {
  if (formType === 'default') return commonRenderers;

  return [
    { tester: linearScaleControlTester, renderer: LinearScaleControl },
    { tester: ratingControlTester, renderer: RatingControl },
    {
      tester: multiSelectCheckboxControlTester,
      renderer: MultiSelectCheckboxControl,
    },
    {
      tester: imageMultichoiceControlTester,
      renderer: ImageMultichoiceControl,
    },
    {
      tester: singleSelectRadioControlTester,
      renderer: SingleSelectRadioControl,
    },
    {
      tester: singleSelectRadioEnumControlTester,
      renderer: SingleSelectRadioEnumControl,
    },
    {
      tester: singleAttachmentControlTester,
      renderer: SingleAttachmentControl,
    },
    {
      tester: mapControlTester,
      renderer: MapControl,
    },
    {
      tester: shapefileUploadControlTester,
      renderer: ShapefileUploadControl,
    },
    ...commonRenderers,
  ];
};
