/*
 *
 * resources/notifications constants
 *
 */

export const LOAD_NOTIFICATIONS_REQUEST = 'app/resources/pages/LOAD_NOTIFICATIONS_REQUEST';
export const LOAD_NOTIFICATIONS_SUCCESS = 'app/resources/pages/LOAD_NOTIFICATIONS_SUCCESS';
export const LOAD_NOTIFICATIONS_ERROR = 'app/resources/pages/LOAD_NOTIFICATIONS_ERROR';

export const MARK_NOTIFICATION_READ_REQUEST = 'app/resources/pages/MARK_NOTIFICATION_READ_REQUEST';
export const MARK_NOTIFICATION_READ_SUCCESS = 'app/resources/pages/MARK_NOTIFICATION_READ_SUCCESS';
export const MARK_NOTIFICATION_READ_ERROR = 'app/resources/pages/MARK_NOTIFICATION_READ_ERROR';

export const MARK_ALL_NOTIFICATIONS_READ_REQUEST = 'app/resources/pages/MARK_ALL_NOTIFICATIONS_READ_REQUEST';
export const MARK_ALL_NOTIFICATIONS_READ_SUCCESS = 'app/resources/pages/MARK_ALL_NOTIFICATIONS_READ_SUCCESS';
export const MARK_ALL_NOTIFICATIONS_READ_ERROR = 'app/resources/pages/MARK_ALL_NOTIFICATIONS_READ_ERROR';
